### ISSUE TITLE
Failed to singing recompiled APK

### ISSUE THREAD

**Issue by Tirititelu** [dana-at-cp/backdoor-apk#10]
The application fail to singing recompiled APK and the new backdoor APK doesn`t work... I can install it i my android.
This is the log:

[*] Generating reverse tcp meterpreter payload...done.
[+] Handle the meterpreter connection at: <MY IP>:4444
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[*] Adding hook in original smali file...done.
[*] Recompiling original project with backdoor...done.
[*] Generating RSA key for signing...done.
[*] Signing recompiled APK...done.
[!] Failed to sign recompiled APK

Do you know what happen?. Thanks!

**Comment by dana-at-cp** [comment]
Hello. Is "jarsigner" in your path? I would guess that it's not. I'll make some minor changes to detect this state and destroy the recompiled, unsigned APK.

**Comment by dana-at-cp** [comment]
New changes on master should make this a non-issue.
