### ISSUE TITLE
Backdoor session closes instantly

### ISSUE THREAD

**Issue by xXDUNNKILLED1Xx** [dana-at-cp/backdoor-apk#100]
As soon as i open my infected apk file, i get a meterpreter session but it instantly closes for "Reason :died"

**Comment by dana-at-cp** [comment]
@xXDUNNKILLED1Xx Please attach the original APK file.

**Comment by xXDUNNKILLED1Xx** [comment]
I will try a different one real quick but it will not let me upload it because the file size is over 10mb, but here is the link to the one i used:

[http://www.apkmirror.com/apk/musical-ly/musical-ly/musical-ly-5-3-3-release/musical-ly-5-3-3-android-apk-download/download/](url)

**Comment by dana-at-cp** [comment]
@xXDUNNKILLED1Xx There are known issues and limitations of Apktool. See #78 for a common issue encountered by users of this project. Also, try some APKs directly from the Google Play store or directly from the developer. For example, the latest version of WhatsApp.

**Comment by xXDUNNKILLED1Xx** [comment]
Thank you, I'll close it since it's nothing wrong with your code but apktool and maybe the apks I have.
