### ISSUE TITLE
Failed to copy RAT smali files

### ISSUE THREAD

**Issue by ijadmy97** [dana-at-cp/backdoor-apk#102]
i have a problem using this tool:

im using metasploit4.14.5

[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[!] Failed to copy RAT smali files

in run.log 

mkdir: created directory ‘/root/backdoor-apk/backdoor-apk/original/smali/io’
mkdir: created directory ‘/root/backdoor-apk/backdoor-apk/original/smali/io/pa’
mkdir: created directory ‘/root/backdoor-apk/backdoor-apk/original/smali/io/pa/listserv’
cp: cannot stat ‘/root/backdoor-apk/backdoor-apk/payload/smali/com/metasploit/stage/MainBroadcastReceiver.smali’: No such file or directory
Forcing cleanup due to a failure or error state!

**Comment by dana-at-cp** [comment]
@ijadmy97 Are you using an older version of Metasploit? That's what it looks like to me.

**Comment by dana-at-cp** [comment]
@ijadmy97 I'm running Metasploit framework 4.14.11 and everything seems normal.
