### ISSUE TITLE
Could not find: d2j-dex2jar

### ISSUE THREAD

**Issue by pacman-vzla** [dana-at-cp/backdoor-apk#103]
When I start apk-backdoor.sh I get the error:
 [!] Check your environment and configuration. Could not find: d2j-dex2jar
Try apt-get install dex2jar and I get the error "The dex2jar package could not be located"

**Comment by peterpt** [comment]
dex2jar can be found in kali repositories or can be downloaded here : 
https://sourceforge.net/projects/dex2jar/

In case you want to install it by apt , then change your repositories to kali and then apply : 
- apt-get update && apt-get install dex2jar

after instalation remove kali repositories from your sources list and do an "apt-get update" with only your linux OS original repositories .

By default dex2jar is a reverse tool , and is not implemented in non pentest linux distributions .
However , if you download it from sourceforge then make sure you install in in /usr/local/sbin folder .

**Comment by dana-at-cp** [comment]
@pacman-vzla Did you get this resolved?

**Comment by pacman-vzla** [comment]
Yeah, thanks <3

**Comment by brianmituka** [comment]
I'm using linux mint. How do I install dex2jar? I've already downloaded it from sourceforgenet and copied the d2j-dex2jar.sh to usr/local/sbin, but i'm still getting the error.

**Comment by hydrahelsing** [comment]
@brianmituka  follow this
If anyone here is using linux mint follow this:
1º Get the download of dex2jar  here https://sourceforge.net/projects/dex2jar/.
2º Open your backdoor-apk.sh with gedit and search for "DEX2JAR = dex2jar" change dex2jar for the path of the file d2j-dex2jar.sh for example DEX2JAR = /home/work/dexjar/d2j-dex2jar.sh.
3º Save the file and enjoy.
