### ISSUE TITLE
Check your environment and configuration. Couldn't find: d2j-dex2jar

### ISSUE THREAD

**Issue by davidphoenix** [dana-at-cp/backdoor-apk#106]
I got this error, no matter what I do:
"Check your environment and configuration. Couldn't find: d2j-dex2jar"
although I've got dex2jar and  changed its permissions (chmod +x). I can even run dex2jar via Bash, but backdoor-apk keeps showing this error. I also copied .sh files to backdoor-apk.sh path, does not work either.
any suggestions?

**Comment by dana-at-cp** [comment]
Make sure the expected program name is in the user's path.

**Comment by brianmituka** [comment]
I'm having the same issue `./backdoor-apk.sh app-release.apk` the apk is in the same directory as the backdoor-apk.sh
