### ISSUE TITLE
[!] Failed to run dx on proguard processed jar file

### ISSUE THREAD

**Issue by ethiccode** [dana-at-cp/backdoor-apk#108]
![screenshot from 2017-05-20 17-04-42](https://cloud.githubusercontent.com/assets/28811396/26275364/70a96644-3d7e-11e7-8892-3d419e9ebff4.png)

**Comment by ethiccode** [comment]
@dana-at-cp

**Comment by dana-at-cp** [comment]
@ethiccode Are you working with a "legit" Facebook APK from the Google Play Store?

**Comment by gangaanonymous** [comment]
Whatever apk i choose it always come with unable to run dx....How to fix it...Plz help

**Comment by dana-at-cp** [comment]
Here's the code in backdoor-apk.sh that is relevant:

```
$DX --dex --output="$MY_PATH/$RAT_APK_FILE" $MY_PATH/bin/classes-processed.jar >>$LOG_FILE 2>&1
rc=$?
if [ $rc != 0 ]; then
  echo "done."
  echo "[!] Failed to run dx on proguard processed jar file"
  cleanup
  exit $rc
fi
echo "done."
```
