### ISSUE TITLE
[!] Failed to locate smali file to hook

### ISSUE THREAD

**Issue by arshiay** [dana-at-cp/backdoor-apk#109]
hi
how fix this?

[*] Running backdoor-apk.sh v0.2.2 on Fri May 26 22:23:26 EDT 2017
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: ************
[?] Please enter an LPORT value: 4444
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[!] Failed to locate smali file to hook

**Comment by dana-at-cp** [comment]
@arshiay Please attach the APK file you were trying to process.
