### ISSUE TITLE
Failed to locate smali file to hook

### ISSUE THREAD

**Issue by Patrickology** [dana-at-cp/backdoor-apk#111]
Hi,

I tried this but it created an error:

![image](https://cloud.githubusercontent.com/assets/28252390/26705673/ea118788-4737-11e7-8a6a-adb27ef03370.png)

What's the problem here?

Thanks in advance!

**Comment by dana-at-cp** [comment]
@Patrickology I'm guessing the APK file is malformed. Did the APK file come from the Google Play store?

**Comment by Patrickology** [comment]
No it didn't..

**Comment by dana-at-cp** [comment]
@Patrickology Please attach the APK file giving you trouble.

**Comment by PunkHack** [comment]
Hi @dana-at-cp, i have the same error trying to create a backdoor in the facebook messenger.

I'm also tried whit another apk, this time was the notebok_V7 (downloaded from this page https://apkpure.com/notebook/mml.RapidNotes.android/download?from=details) and doesn't work either.
This is the error: [*] Aligning recompiled APK...done.
[!] Failed to align recompiled APK

**Comment by Patrickology** [comment]
I can't even remember which apk it was, not from the Playstore anyway. No worries about it bro

**Comment by dana-at-cp** [comment]
@Patrickology I reran some tests today with v0.2.2. and its working on APK files that I obtained from the Play Store.

Unofficial APK files cannot be supported since there are a number of things that could be wrong with those samples.
