### ISSUE TITLE
[!] Failed to generate RAT APK file

### ISSUE THREAD

**Issue by anonymouskillerbr1** [dana-at-cp/backdoor-apk#113]
Hello have you tried using the backdoor-apk and have data the next error, [!] Failed to generate RAT APK file. I've already put the original APK in the backdoor-apk folder, backdoor-apk, and even then the error that I showed above, how can I fix this?

**Comment by dana-at-cp** [comment]
@anonymouskillerbr1 Please share the APK file you are trying to use.

**Comment by anonymouskillerbr1** [comment]
I removed all the packages and installed again, it worked normal. Thank you.


2017-07-17 10:48 GMT-03:00 Dana James Traversie <notifications@github.com>:

**Comment by dana-at-cp** [comment]
@anonymouskillerbr1 Ok. Thanks for the update.
