### ISSUE TITLE
failed in recompiling

### ISSUE THREAD

**Issue by Doutianbao** [dana-at-cp/backdoor-apk#115]
Use 3 examples, 2 fails. what a pity.

All occur at the point:
[!] Failed to recompile original project with backdoor

The process before goes smoothly.

**Comment by dana-at-cp** [comment]
@Doutianbao See anything interesting in the run.log file?

**Comment by Doutianbao** [comment]
Building resources...
W: warning: string 'menu_move' has no default translation.
W: /root/tools/android/backdoor-apk/backdoor-apk/original/res/values/public.xml:165: error: invalid symbol: 'do'
W: 
W: /root/tools/android/backdoor-apk/backdoor-apk/original/res/values/public.xml:386: error: invalid symbol: 'do'
W: 
W: /root/tools/android/backdoor-apk/backdoor-apk/original/res/values/public.xml:563: error: invalid symbol: 'if'
W: 
W: /root/tools/android/backdoor-apk/backdoor-apk/original/res/values/public.xml:1719: error: invalid symbol: 'do'
W: 
W: /root/tools/android/backdoor-apk/backdoor-apk/original/res/values/public.xml:1895: error: invalid symbol: 'if'
W: 
W: /root/tools/android/backdoor-apk/backdoor-apk/original/res/values/public.xml:2395: error: invalid symbol: 'do'
W: 
W: /root/tools/android/backdoor-apk/backdoor-apk/original/res/values/public.xml:2571: error: invalid symbol: 'if'
W: 
W: /root/tools/android/backdoor-apk/backdoor-apk/original/res/values/public.xml:5090: error: invalid symbol: 'do'
W: 
W: /root/tools/android/backdoor-apk/backdoor-apk/original/res/values/public.xml:5314: error: invalid symbol: 'do'
W: 
W: /root/tools/android/backdoor-apk/backdoor-apk/original/res/values/public.xml:5490: error: invalid symbol: 'if'
W: 
W: /root/tools/android/backdoor-apk/backdoor-apk/original/res/layout/a.xml:4: error: Error: No resource found that matches the given name (at 'layout' with value '@layout/common_titlebar_layout').
W: 
W: /root/tools/android/backdoor-apk/backdoor-apk/original/res/layout/a0.xml:6: error: Error: No resource found that matches the given name (at 'style' with value '@style/dm_boundary_line').
W: 
W: /root/tools/android/backdoor-apk/backdoor-apk/original/res/layout/a0.xml:9: error: Error: No resource found that matches the given name (at 'layout' with value '@layout/ad_vip_item').
W: 
W: /root/tools/android/backdoor-apk/backdoor-apk/original/res/layout/a0.xml:11: error: Error: No resource found that matches the given name (at 'style' with value '@style/dm_boundary_line').
W: 
W: /root/tools/android/backdoor-apk/backdoor-apk/original/res/layout/a1.xml:14: error: Error: No resource found that matches the given name (at 'style' with value '@style/dm_special_btn_normal_style').
W: 
W: /root/tools/android/backdoor-apk/backdoor-apk/original/res/layout/a3.xml:4: error: Error: No resource found that matches the given name (at 'style' with value '@style/DialogTitleStyle').
W: 
W: /root/tools/android/backdoor-apk/backdoor-apk/original/res/layout/a3.xml:6: error: Error: No resource found that matches the given name (at 'style' with value '@style/DialogTitleStyle').
W: 
W: /root/tools/android/backdoor-apk/backdoor-apk/original/res/layout/a3.xml:9: error: Error: No resource found that matches the given name (at 'style' with value '@style/DialogOKStyle').

**Comment by Doutianbao** [comment]
#78 Maybe the same problem

**Comment by dana-at-cp** [comment]
@Doutianbao You are correct sir. Try other APKs. You will have better luck with APKs from the Play Store.
