### ISSUE TITLE
i have weird error [./backdoor-apk.sh: line 128: $LOG_FILE: ambiguous redirect]

### ISSUE THREAD

**Issue by bleedweedsuz** [dana-at-cp/backdoor-apk#117]
root@kali:~/Desktop/backdoor-apk# ./backdoor-apk.sh FILE.apk 
./backdoor-apk.sh: line 216: $LOG_FILE: ambiguous redirect
[*] Running backdoor-apk.sh v0.2.2 on Fri Sep  1 16:34:44 +0545 2017
./backdoor-apk.sh: line 128: $LOG_FILE: ambiguous redirect
[!] Check your environment and configuration. Couldn't find: msfvenom

**//i saw consult_which function in shell file if i comment on exit $rc i would give this error**

[*] Running backdoor-apk.sh v0.2.2 on Fri Sep  1 16:34:18 +0545 2017
./backdoor-apk.sh: line 128: $LOG_FILE: ambiguous redirect
[!] Check your environment and configuration. Couldn't find: msfvenom
./backdoor-apk.sh: line 128: $LOG_FILE: ambiguous redirect
[!] Check your environment and configuration. Couldn't find: d2j-dex2jar
./backdoor-apk.sh: line 128: $LOG_FILE: ambiguous redirect
[!] Check your environment and configuration. Couldn't find: unzip
./backdoor-apk.sh: line 128: $LOG_FILE: ambiguous redirect
[!] Check your environment and configuration. Couldn't find: keytool
./backdoor-apk.sh: line 128: $LOG_FILE: ambiguous redirect
[!] Check your environment and configuration. Couldn't find: jarsigner
./backdoor-apk.sh: line 128: $LOG_FILE: ambiguous redirect
[!] Check your environment and configuration. Couldn't find: apktool
./backdoor-apk.sh: line 128: $LOG_FILE: ambiguous redirect
[!] Check your environment and configuration. Couldn't find: third-party/proguard5.3.2/lib/proguard
./backdoor-apk.sh: line 128: $LOG_FILE: ambiguous redirect
[!] Check your environment and configuration. Couldn't find: third-party/android-string-obfuscator/lib/aso
./backdoor-apk.sh: line 128: $LOG_FILE: ambiguous redirect
[!] Check your environment and configuration. Couldn't find: third-party/android-sdk-linux/build-tools/25.0.2/dx
./backdoor-apk.sh: line 128: $LOG_FILE: ambiguous redirect
[!] Check your environment and configuration. Couldn't find: third-party/android-sdk-linux/build-tools/25.0.2/zipalign
./backdoor-apk.sh: line 119: $LOG_FILE: ambiguous redirect
[!] Original APK file specified is not valid

**//so what's wrong with this shell file i m confused.  *.***
**what configuration????
what environment????**

**Comment by dana-at-cp** [comment]
@bleedweedsuz As the messages clearly state ... your environment/configuration is in a bad state. You are either missing dependencies required by backdoor-apk or somehow they are not in the user path.

**Comment by Joao-Bonifacio** [comment]
please how can i install this dependency?

third-party/android-string-obfuscator/lib/aso

I've searched a lot and couldn't find the solution.

**Comment by RKRAKER** [comment]
Olá, os arquivos já estão instalados , mas estão sem permissão , tenta dar "chmod +X " , deu certo comigo :)

**Comment by SICADATRIDIMENSIONAL** [comment]
@RKRAKER os meus não estão, sabe me dizer qual comando para baixa-los? Eu só tenho o metasploit
