### ISSUE TITLE
Couldn't find: msfvenom

### ISSUE THREAD

**Issue by Palmus84** [dana-at-cp/backdoor-apk#130]
Kali Linux 2018.1 64bit
TheFatRat v1.9.5
Metasploit v4.16.43-dev
Backdoor-apk v.0.2.3
I'll write my issue:

root@kali:~/backdoor-apk/backdoor-apk# ./backdoor-apk.sh
./backdoor-apk.sh: riga 239: $LOG_FILE: redirezione ambigua
         
[*] Running backdoor-apk.sh v0.2.3 on lun  5 mar 2018, 21.16.16, CET
./backdoor-apk.sh: riga 129: $LOG_FILE: redirezione ambigua
[!] Check your environment and configuration. Couldn't find: msfvenom

Could you help me? Thanks a lot.

**Comment by dana-at-cp** [comment]
@Palmus84 I cannot provide support for environment issues. Sorry.

**Comment by ghost** [comment]
copy the folder "backdoor-apk" to /usr/share/ and run again... :)

**Comment by ghost** [comment]
> Kali Linux 2018.1 64bit
> TheFatRat v1.9.5
> Metasploit v4.16.43-dev
> Backdoor-apk v.0.2.3
> I'll write my issue:
> 
> root@kali:~/backdoor-apk/backdoor-apk# ./backdoor-apk.sh
> ./backdoor-apk.sh: riga 239: $LOG_FILE: redirezione ambigua
> 
> [*] Running backdoor-apk.sh v0.2.3 on lun 5 mar 2018, 21.16.16, CET
> ./backdoor-apk.sh: riga 129: $LOG_FILE: redirezione ambigua
> [!] Check your environment and configuration. Couldn't find: msfvenom
> 
> Could you help me? Thanks a lot.

copy the folder "backdoor-apk" to /usr/share/ and run again... :)

**Comment by ZWJGithubjoin** [comment]
Check your environment and configuration. Couldn't find: baksmali
  how to solve？ Install basksmali？

**Comment by pretech86** [comment]
thanks my dear it working now

**Comment by strikerkill** [comment]
1
