### ISSUE TITLE
[!] Failed to recompile original project with backdoor

### ISSUE THREAD

**Issue by sailyajit** [dana-at-cp/backdoor-apk#132]
when i run the .sh as : ./backdoor-apk.sh Snapdeal.apk

The output as on the run.log file comes out...please help.
[run.log](https://github.com/dana-at-cp/backdoor-apk/files/1977182/run.log)

**Comment by LinkG** [comment]
+1 same, I had gotten it to work before, but after I changed distros its not working anymore

**Comment by dana-at-cp** [comment]
From your run.log file it looks like you are missing some of the 32 bit libs.

Read through the comments under issue #30

**Comment by allex4freedom** [comment]
Hello i have this message when i try :
Failed to recompile original project with backdoor
Any soution ?
[run.log](https://github.com/dana-at-cp/backdoor-apk/files/3497019/run.log)
