### ISSUE TITLE
[!] Failed to locate smali file to hook ?? :/

### ISSUE THREAD

**Issue by grimmpotter** [dana-at-cp/backdoor-apk#133]
_Hello, i hope you're all doing good..
while i was trying to backdoor an apk i got this error 
"" [!] Failed to locate smali file to hook ""

with facebook messenger apk
how can i fix it ? please.

Thanks in advance ~~_
![Uploading Screenshot from 2018-05-12 15-35-08.png…]()

**Comment by fedi966** [comment]
the same problem any solution?

**Comment by fedi966** [comment]
any advices??

**Comment by dana-at-cp** [comment]
@grimmpotter @fedi966 @glenn2148 Hooking logic is different in the next release. I may have it pushed out later today or later this week.

**Comment by dana-at-cp** [comment]
Should be fixed in 0.2.4.

**Comment by glenn2148** [comment]
fantastic work dana-at-cp, first time in 6 weeks i have completed a job, thanks
Question:can you rename an apk after you have installed the back door without destroying it???

**Comment by kelvinmatheka** [comment]
How did you fix it
