### ISSUE TITLE
 Unable to add persistence hook due to missing permission

### ISSUE THREAD

**Issue by mechaadi** [dana-at-cp/backdoor-apk#134]
help me with is, I made an app with android studio today and generated a signed apk but unfortunately something is not working properly

`[*] Generating RAT APK file...done.`
`[*] Decompiling original APK file...done.`
`[*] Decompiling RAT APK file...done.`
`[*] Merging permissions of original and payload projects...done.`
`[*] Running proguard on RAT APK file...done.`
`[*] Decompiling obfuscated RAT APK file...done.`
`[*] Creating new directories in original project for RAT smali files...done.`
`[*] Copying RAT smali files to new directories in original project...done.`
`[*] Fixing RAT smali files...done.`
`[*] Obfuscating const-string values in RAT smali files...unable to write 'random state
done.`
`[*] Locating smali file to hook in original project...done.`
`[*] Adding hook in original smali file...done.`
`[+] Unable to add persistence hook due to missing permission`
`[*] Recompiling original project with backdoor...done.`
`[!] Failed to recompile original project with backdoor`

[lrun.log](http://www.mediafire.com/file/9e47djl8ge7iwe3/run.log)

**Comment by Dylan433447** [comment]
same here

**Comment by mechaadi** [comment]
Hey, @Dylan433447 try this 
#10033

**Comment by mechaadi** [comment]
Hey try this #10033

#10033

**Comment by chanda1998** [comment]
where to add this #10033

**Comment by mechaadi** [comment]
https://github.com/rapid7/metasploit-framework/issues/10033
