### ISSUE TITLE
Necessary:Problems creating a Backdoor.apk file

### ISSUE THREAD

**Issue by a-zamani** [dana-at-cp/backdoor-apk#143]
Hello.
**I know that I have to put it in "TheFatRat", but the problem is not "natural"!
The problem is your software**

When I'm creating a "backdoor" file for Android
After choosing Hook 5 Fat, it does not get the "backdoor" file and it does not fix it!
The steps I take:

    [05] Backdooring Original apk [Instagram, Line,etc] .
    I use "NGROK" for "LPORT" and "LHOST".
    Path : /root/Desktop/flappybird.apk
    [ 2 ] Use old Fatrat method
    [ 3 ] android/meterpreter/reverse_tcp
    Hook 5

ERROR : 
[*] Decompiling payload APK..
Traceback (most recent call last):
	2: from tools/apkembed.rb:168:in `<main>'
	1: from tools/apkembed.rb:168:in `open'
tools/apkembed.rb:168:in `initialize': No such file or directory @ rb_sysopen - temp/original/AndroidManifest.xml (Errno::ENOENT)
 
\e[1;31m 
[x] There was an error in the creation of your RAT APK file , the possible reasons are :
- The architecture of the file is not for android
- The original APK is protected
- It was not possible to inject the payload in the hook you selected (in this case select a different hook point)
Check log file at : /root/TheFatRat-master/logs/apk-old.log

**Comment by a-zamani** [comment]
**Help Me Please**

**Comment by dana-at-cp** [comment]
@a-zamani I can't support TheFatRat. With that said, a new release of backdoor-apk is coming soon.
