### ISSUE TITLE
2 errors launch backdoor-apk

### ISSUE THREAD

**Issue by beurre28** [dana-at-cp/backdoor-apk#146]
Hello Boy,

I hope you are well !
I have problem with your script. 
I send you my problem in attachment, it will be clearer.

Thx advance,
Antho.

![backdoor-apk-principal error](https://user-images.githubusercontent.com/41798101/43330816-9191579a-91c4-11e8-8226-94c610fcac92.PNG)
![backdoor-apk-line 239](https://user-images.githubusercontent.com/41798101/43330826-961f114e-91c4-11e8-8ca3-a4f1890ede15.PNG)

**Comment by dana-at-cp** [comment]
@beurre28 Your environment is not setup correctly.
