### ISSUE TITLE
Failed to decompile original APK file

### ISSUE THREAD

**Issue by TryHard3r** [dana-at-cp/backdoor-apk#147]
Hello, guy！
When I run your script，the terminal display "**Failed to decompile original APK file**".
I have tried multiple apk files，the result is the same.
Maybe I need your help

**Comment by devilankur18** [comment]
@VisualLine I have also faced this. I got it working by follow the directory as per shown in the README, Also the apk should be in script directory.

**Comment by dana-at-cp** [comment]
@TryHard3r Move the APK file into the same directory as the backdoor-apk.sh script.

**Comment by pretech86** [comment]
thsnks my dear for this project, hope for more projects from you 
i face the problem ( failed to decompile the file ) and i transfered the apk file to the same directory but still failed , can you help me please ?
