### ISSUE TITLE
[!] Failed to decompile original APK file

### ISSUE THREAD

**Issue by littleheary** [dana-at-cp/backdoor-apk#150]
[!] Failed to decompile original APK file
how to solve this?

**Comment by sanjeevpk** [comment]
Same error I am also facing, could you please let us know how to resolve this issue. I have installed apktool and zipalign but still facing the issue even for a smaller kb apks.

**Comment by dana-at-cp** [comment]
@littleheary @sanjeevpk Depends on the APK. Apktool doesn't work on every APK but it should work on most APKs that come from the legit Google Play Store.

**Comment by waleed99100** [comment]
i solved most problems in new issues up check it

**Comment by dana-at-cp** [comment]
@littleheary Try to decompile the APK using Apktool alone. If it fails then you found the root cause. :)

**Comment by pretech86** [comment]
i solved this by choosing a asmall size app like 14 mb pdf reader
