### ISSUE TITLE
using it over WAN

### ISSUE THREAD

**Issue by deltadroid** [dana-at-cp/backdoor-apk#152]
can it be used over WAN along with ngrok?
I tried couple of times but the meterpreter sessions are not captured. is there any way?

**Comment by dana-at-cp** [comment]
@deltadroid I don't know much about ngrok but I have tested android/meterpreter/reverse_https payloads over the Internet/WAN that were created as part of backdoor-apk.sh.

**Comment by dana-at-cp** [comment]
@deltadroid Version 0.2.3 had issues with more recent versions of Metasploit/msfvenom. All of those issues have been resolved in versions 0.2.4 and 0.2.4a. I would try to use ngrok again with the latest version of backdoor-apk.

Also, it wouldn't hurt to do initial tests on a LAN and WAN without ngrok before retesting over the Internet with ngrok.
