### ISSUE TITLE
Failed to sign recompiled APK

### ISSUE THREAD

**Issue by mohammadrezza** [dana-at-cp/backdoor-apk#153]
jar signer says unable to open jar file , what should i do ?

**Comment by dana-at-cp** [comment]
@mohammadrezza anything interesting in run.log?

**Comment by dana-at-cp** [comment]
@mohammadrezza FYI. The script depends on some directories included in the project. If you move the backdoor-apk.sh script to some new location it will break a lot of things.

**Comment by mohammadrezza** [comment]
the ending lines of run.log is:
`Value of from_date_str: 2012/09/19 07:35:
Value of validity: 30000
jarsigner: unable to open jar file: /root/Downloads/backdoor-apk/backdoor-apk/original/dist/../../SHAREit_3.5.48_Android.apk
Forcing cleanup due to a failure or error state!
`
i ran this command : 
`root@kali-arm64:~/Downloads/backdoor-apk/backdoor-apk# sudo ./backdoor-apk.sh ../../SHAREit_3.5.48_Android.apk `

**Comment by dana-at-cp** [comment]
@mohammadrezza This is a very simple bug but as a workaround move the APK file to the same directory as the backdoor-apk.sh script.

**Comment by dana-at-cp** [comment]
@mohammadrezza This is fixed in version 0.2.4a.
