### ISSUE TITLE
solved! common error with backdoor-apk

### ISSUE THREAD

**Issue by waleed99100** [dana-at-cp/backdoor-apk#154]
hello as i tired i'm running kali64 i fixed my problem one after another and i want to share knowledge fixing common problem 

firstly open terminal and type the following commands
to install java jdk
`apt-get install jdk 10`
apktool last
`apt-get install apktool`
lib64 witch required
`sudo apt-get install lib32zl lib32ncurses5 lib32stdc++6`
"field to recompile original project with apktool"
by installing zipalign
`apt-get install zipalign`
"field to align apk"
by
`sudo apt-get install lib32stdc++6 lib32z1 lib32z1-dev`
that all now no error

**Comment by dana-at-cp** [comment]
@waleed99100 Apktool is required and so are the 32/64 bit libraries. The zipalign tool is included as a third-party dependency. A recent version of a JDK is required as well to do the signing after recompilation.

FYI. The output of backdoor-apk and entries in run.log should have given you some clues.

Sorry you had so much trouble.

On a side note, version 0.2.4 was just committed minutes ago.
