### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by glenn2148** [dana-at-cp/backdoor-apk#155]
1, after i have recompiled a new version with a virus, can it be renamed and still work as designed?? 

2: If running backdoor-apk on a program fails, and i imeadatly run it again (same commands) and it runs with  no problems will it be ok???  (i have done this several times but not tested either program)

thanks

**Comment by dana-at-cp** [comment]
Answers below:

1. You can rename the repackaged APK file with no issue or loss in functionality. If you are talking about changing the name of the application displayed after the APK is installed then there is much more involved and much more that can go wrong.

2. If you observed this behavior on version 0.2.3 then it is likely that the issue(s) is resolved in version 0.2.4a. If you are seeing this behavior in version 0.2.4a then I would have test with the APK file and/or see the run.log output on failure.
