### ISSUE TITLE
Opération failed : 1

### ISSUE THREAD

**Issue by kali2525** [dana-at-cp/backdoor-apk#163]
Hi everybody
I use backdoor to merge payload in apk game the build done and the session done 
But the problèm when i use command i get (Opération failed : 1)
What i do ?

**Comment by WiredLife** [comment]
No needed permission/s granted
go to the app permissions in android an check the needed permission/s

**Comment by kali2525** [comment]
@WiredLife 
Itried to transfer the permission from the payload AndroidManifest.xml file  to original but the application did not work when I returned it to the original form

**Comment by dana-at-cp** [comment]
Make sure you are using the latest stable version of msfvenom.
