### ISSUE TITLE
install failed 

### ISSUE THREAD

**Issue by ghost** [dana-at-cp/backdoor-apk#164]
hello i want install your script in kali nethunter termux android but i have one error.

[*] Running backdoor-apk.sh v0.2.4a on Thu Dec 20 09:48:04 UTC 2018
[!] Check your environment and configuration. Couldn't find: baksmali

Thanks for your help

**Comment by ashish111821** [comment]
I'm also having the same problem

**Comment by fipso** [comment]
Hey,
u can get baksmali here -> https://github.com/JesusFreke/smali/
just download the jar and the the script from here https://github.com/JesusFreke/smali/blob/master/scripts/baksmali and add the script to PATH

**Comment by ghost** [comment]
ok thanks

**Comment by ghost** [comment]
hello fipso please give me the step because no work.
├─[~/backdoor-apk-master/backdoor-apk]           └─[$] ls                                         Calculette.apk       cleanup.sh  run.log         META-INF             com         smali-master    backdoor-apk.sh      java        third-party     baksmali-2.2.5.jar   javax                       baksmali.properties  org

[*] Running backdoor-apk.sh v0.2.4a on Mon Jan  7 11:42:31 CET 2019                               [!] Check your environment and configuration. Couldn't find: baksmali

**Comment by ashish111821** [comment]
Try updating and upgrading termux

**Comment by ashish111821** [comment]
Pkg upgrade

**Comment by McCreamy** [comment]
Help fipso, how do i install baksmali???

**Comment by McCreamy** [comment]
> Hey,
> u can get baksmali here -> https://github.com/JesusFreke/smali/
> just download the jar and the the script from here https://github.com/JesusFreke/smali/blob/master/scripts/baksmali and add the script to PATH

how do i install it ???

**Comment by Sufiyan0335** [comment]
Same problem how to install baksmali???

**Comment by Sufiyan0335** [comment]
> Hey,
> u can get baksmali here -> https://github.com/JesusFreke/smali/
> just download the jar and the the script from here https://github.com/JesusFreke/smali/blob/master/scripts/baksmali and add the script to PATH

How to install it??

**Comment by Sufiyan0335** [comment]
I think this method is work for you

> > Hey,
> > u can get baksmali here -> https://github.com/JesusFreke/smali/
> > just download the jar and the the script from here https://github.com/JesusFreke/smali/blob/master/scripts/baksmali and add the script to PATH
> 
> how do i install it ???

Try this 
https://null-byte.wonderhowto.com/how-to/embed-metasploit-payload-original-apk-file-part-2-do-manually-0167124/

**Comment by zer0overflow** [comment]
Run these commands 
`git clone https://github.com/JesusFreke/smali/`
`cd smali/blob/master/scripts/baksmali`
`export PATH=$PATH:$(pwd)`

I can't find the baksmali.jar file. If you get it from somewhere paste it to the folder where your baksmali script is there

**Comment by zer0overflow** [comment]
Ok here's an update. Download backsmali.jar from here
https://bitbucket.org/JesusFreke/smali/downloads/
Then rename it to baksmali.jar and copy it to your baksmali script location.
Cheers! Give me a follow on instagram it's @zero.overflow

**Comment by hakbibi** [comment]
> add the script to PATH

how can i add the script to path?

**Comment by bvdx199** [comment]
what does $PATH mean I hear it alot

**Comment by robinhamie123** [comment]
my Friends what path i put baksmali in it ???? there is to much files wich one  of these i put it and where

**Comment by robinhamie123** [comment]
> Ok here's an update. Download backsmali.jar from here
> https://bitbucket.org/JesusFreke/smali/downloads/
> Then rename it to baksmali.jar and copy it to your baksmali script location.
> Cheers! Give me a follow on instagram it's @zero.overflow
............................................................................................................
my Friend what is the script location where i,ll copy it to ????

**Comment by MetehanSimsekk** [comment]
https://bitbucket.org/JesusFreke/smali/downloads/ wrong proxy settings bro.ı think broken

**Comment by amrulizwan** [comment]
> Hey,
> u can get baksmali here -> https://github.com/JesusFreke/smali/
> just download the jar and the the script from here https://github.com/JesusFreke/smali/blob/master/scripts/baksmali and add the script to PATH

  if you tell, tell clearly, which path!

**Comment by MetehanSimsekk** [comment]
Can you send me the link of my video ?

Amrul Izwan <notifications@github.com>, 24 Kas 2020 Sal, 10:03 tarihinde
şunu yazdı:
