### ISSUE TITLE
[!] Failed to recompile original apk project with backdoor

### ISSUE THREAD

**Issue by dsx12** [dana-at-cp/backdoor-apk#165]
The scripts functions worked fine until the recompiling function was called it exited with the error:

"[!] Failed to recompile original apk project with backdoor"

I have noticed there are some current bugs with apktool going around on most debian operating systems.

Is there a method to configure this script to run on windows? I tried injecting metasploit payloads into my original apk on windows and received a error on widows also.

Does anyone have an explanation or fix? please help!

**Comment by dsx12** [comment]
Is there a alternative tool other than apktool to rebuild decompiled apks that successfully works?

**Comment by stevanuscolonne** [comment]
@dsx12 try to replace apktool.jar file from its official website. I've tried and recompile succes.

**Comment by scr1k** [comment]
> ap
 @stevanuscolonne 
could u tell me where should i replace?

**Comment by threst** [comment]
https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.3.4.jar 
it's ok

**Comment by pretech86** [comment]
@threst where ishould paste it after downloades 
thanks a lot

**Comment by simoohara2** [comment]
https://ibotpeaches.github.io/Apktool/install/

**Comment by dana-at-cp** [comment]
#168
