### ISSUE TITLE
installing error 

### ISSUE THREAD

**Issue by pretech86** [dana-at-cp/backdoor-apk#170]
when i run the tool i get this error 

[*] Running backdoor-apk.sh v0.2.4a on Thu 09 May 2019 05:39:05 PM EDT
./backdoor-apk.sh: line 134: $LOG_FILE: ambiguous redirect
[!] Check your environment and configuration. Couldn't find: msfvenom

**Comment by dana-at-cp** [comment]
@pretech86 Try this stackoverflow Q&A: https://stackoverflow.com/questions/2462385/getting-an-ambiguous-redirect-error

The following message is letting you know that 'msfvenom' is not in your path:

[!] Check your environment and configuration. Couldn't find: msfvenom
