### ISSUE TITLE
no reverse connections 

### ISSUE THREAD

**Issue by pretech86** [dana-at-cp/backdoor-apk#173]
thanks for the tool but all steps finished but i didn't recieved a reverse connection 
i used msfconsole -r backdoor-apk.rc also i used the third party applications

**Comment by dana-at-cp** [comment]
> thanks for the tool but all steps finished but i didn't recieved a reverse connection
> i used msfconsole -r backdoor-apk.rc also i used the third party applications

Need more information. Are you attempting to receive a reverse connection on the same LAN/subnet or across the Internet for example?
