### ISSUE TITLE
 Failed to run baksmali on classes.dex created for Java class files

### ISSUE THREAD

**Issue by rrnamitesh** [dana-at-cp/backdoor-apk#177]
I keep on getting this error.

**Comment by icecliffs** [comment]
Metoo

**Comment by CiberSecLabs** [comment]
same as above -- Failed to run baksmali on classes.dex created for Java class files .. Please Help !  thanks

**Comment by Alexandre-ux** [comment]
Estou com o mesmo problema.
Alguém sabe a solução?plis
