### ISSUE TITLE
Failed to locate smali file to hook

### ISSUE THREAD

**Issue by justMSARahat** [dana-at-cp/backdoor-apk#178]
[*] Running backdoor-apk.sh v0.2.4a on Wed 02 Oct 2019 03:18:49 PM +06
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: ------------
[?] Please enter an LPORT value: ----
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 2
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Decompiling original APK file...done.
[*] Locating smali file to hook in original project...done.
[!] Failed to locate smali file to hook

**Comment by MrFey** [comment]
hey did you find how to fix that problem ?

**Comment by ll3N1GmAll** [comment]
I see this was a bug and was supposed to have been fixed back in 2017. I am still seeing this issue on numerous APKs.

**Comment by xiaofengjue** [comment]
> I see this was a bug and was supposed to have been fixed back in 2017. I am still seeing this issue on numerous APKs.

ditto

**Comment by hartmanfrost** [comment]
Just replace `smali_file_to_hook=$MY_PATH/original/smali/$android_class.smali` to `smali_file_to_hook=$(find $MY_PATH/original/smali/ -name '*$android_class*')` in script file.

**Comment by HeYiKunclass** [comment]
> 

Thank you very much

**Comment by dana-at-cp** [comment]
#191 This logic is being improved.
