### ISSUE TITLE
[!] Failed to align recompiled APK and date: invalid date ‘Fri Jan 15 07:11:31 2112’

### ISSUE THREAD

**Issue by jacobrohit** [dana-at-cp/backdoor-apk#179]
[*] Running backdoor-apk.sh v0.2.4a on Wed 18 Dec 2019 02:09:27 PM IST
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 2
[*] Decompiling original APK file...done.
[*] Locating smali file to hook in original project...done.
[+] Package where RAT smali files will be injected: com/instagram/android
[+] Smali file to hook RAT payload: com/instagram/app/InstagramAppShell.smali
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Injecting helpful Java classes in RAT APK file...done.
[*] Creating new directory in original package for RAT smali files...done.
[+] Inject package path: com/instagram/android/vrfnp
[+] Generated new smali class name for MainBroadcastReceiver.smali: Gfsyx
[+] Generated new smali class name for MainService.smali: Ykbdc
[+] Generated new smali class name for Payload.smali: Nxlsm
[+] Generated new smali class name for StringObfuscator.smali: Bcmfo
[+] Generated new smali method name for StringObfuscator.obfuscate method: wxkzu
[+] Generated new smali method name for StringObfuscator.unobfuscate method: hfmhs
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
**date: invalid date ‘Fri Jan 15 07:11:31 2112’**
[*] Generating RSA key for signing...done.
[*] Signing recompiled APK...done.
[*] Verifying signed artifacts...done.
[*] Aligning recompiled APK...done.
**[!] Failed to align recompiled APK**

**Comment by dual-somkietacode** [comment]
showme the run.log
