### ISSUE TITLE
erro smali

### ISSUE THREAD

**Issue by zackvirushacke** [dana-at-cp/backdoor-apk#180]
Failed to locate smali file to hook ?

**Comment by Pr-X374** [comment]
see the run.log file

**Comment by Pr-X374** [comment]
I get the same problem last week your apk android:name atribut dont exisit in the manifest you have to find it manualy and replace $android_class by $total_pakage/$android_name . Where android name shall be Main or .Main or MainActivty

**Comment by dual-somkietacode** [comment]
> Failed to locate smali file to hook ?

I get the same problem last week your apk android:name atribut dont exisit in the manifest you have to find it manualy and replace $android_class by $total_pakage/$android_name . Where android name shall be Main or .Main or MainActivty

**Comment by dana-at-cp** [comment]
#191 Some improvements are being implemented.
