### ISSUE TITLE
Failed to locate smali file to hook

### ISSUE THREAD

**Issue by delgiu87** [dana-at-cp/backdoor-apk#183]
run.log   I think some upgrade in google certificate? how can solve this? we should upgrade something? just tried with other apps

I: Decoding file-resources...
W: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/common_google_signin_btn_text_light_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png". Renaming it to *.png.
I: Decoding values */* XMLs...

**Comment by hartmanfrost** [comment]
Just replace `smali_file_to_hook=$MY_PATH/original/smali/$android_class.smali` to `smali_file_to_hook=$(find $MY_PATH/original/smali/ -name '*$android_class*')` in script file.

**Comment by dana-at-cp** [comment]
#191 There are some issues identified with this logic. I'm working on a fix.
