### ISSUE TITLE
Couldn't find: baksmali

### ISSUE THREAD

**Issue by wesley006** [dana-at-cp/backdoor-apk#184]
[*] Running backdoor-apk.sh v0.2.4a on Sat Apr  4 19:46:32 -03 2020
[!] Check your environment and configuration. Couldn't find: baksmali

**Comment by illusion77** [comment]
i have the same question...and how do i to install baksmali?

**Comment by BotSabugogrosso** [comment]
#git clone https://github.com/JesusFreke/smali.git
#cd smali
#./gradlew

**Comment by steef98** [comment]
________
         / ______ \
         || _  _ ||
         ||| || |||          AAAAAA   PPPPPPP   KKK  KKK
         |||_||_|||         AAA  AAA  PPP  PPP  KKK KKK
         || _  _o|| (o)     AAA  AAA  PPP  PPP  KKKKKK
         ||| || |||         AAAAAAAA  PPPPPPPP  KKK KKK
         |||_||_|||         AAA  AAA  PPP       KKK  KKK
         ||______||         AAA  AAA  PPP       KKK  KKK
        /__________\
________|__________|__________________________________________
       /____________\
       |____________|            Dana James Traversie

[*] Running backdoor-apk.sh v0.2.4a on Sal May 26 05:18:46 +03 2020
[!] Check your environment and configuration. Couldn't find: baksmali





HELPPPP

**Comment by EliasHridoy** [comment]
@BotSabugogrosso 
I tried your procedure but not worked.

**Comment by Summer20130725** [comment]
**apt search baksmali**

**Comment by fkay9** [comment]
I am having the same problem as well

**Comment by ashkorehennessy** [comment]
try
sudo apt install smali apktool

**Comment by r1th1k** [comment]
> try
> sudo apt install smali apktool

it worked

**Comment by xiaofengjue** [comment]
> > try
> > sudo apt install smali apktool
> 
> it worked

work nimane

**Comment by xiaofengjue** [comment]
> try
> sudo apt install smali apktool

thank u，it works
