### ISSUE TITLE
Backdoor-apk + Ngrok tcp + msfconsole not working!

### ISSUE THREAD

**Issue by vaerda** [dana-at-cp/backdoor-apk#188]
![bacdoorapk+msfconsole+ngrok-error](https://user-images.githubusercontent.com/66242421/85450311-42c54800-b55e-11ea-9d7e-28824fad96e6.png)

Hi, i've just created a infected app with backdoor-apk and it decompilation and compilation it's all right, but when i try to connect the backdoor with msfconsole says was not created, when the apk has been already executed by the android. 

I hope yo can help me with this trouble, because i don't have any idea what's going bad.
Love u and kisses, amazing backdoor creation tool.

**Comment by dana-at-cp** [comment]
@vaerda Apologies but there's so much that could be going on here that I cannot fully troubleshoot or support. Create a version with an easily verifiable communication channel to rule out Ngrok or other network issues.
