### ISSUE TITLE
Failed to recompile original project with backdoor

### ISSUE THREAD

**Issue by ALBERT00** [dana-at-cp/backdoor-apk#19]
The issue i have, comes up when backdoor-apk recompiles the project with the backdoor.
Error: Failed to recompile original project with backdoor
I read the Issue #17 and try the solution, but it doesn't work.
Any ideas?

**Comment by dana-at-cp** [comment]
Share the run.log output if you can.

**Comment by devrajashwin** [comment]
sir can u tell me where to place the apk file original to make as rat,
1,i found this 

root@venum:~/Downloads/backdoor-apk-master/backdoor-apk# ./backdoor-apk.sh 
rm: cannot remove 'Rat.apk': No such file or directory
rm: cannot remove 'perms.tmp': No such file or directory
rm: cannot remove 'persistence.hook': No such file or directory
rm: cannot remove 'obfuscate.method': No such file or directory
rm: cannot remove 'signing.keystore': No such file or directory
Type LHOST: XXX.XX.XX.XX
Type LPORT: 4444
[!] No original APK file specified
