### ISSUE TITLE
Would you like to help with an open source project???

### ISSUE THREAD

**Issue by Morsmalleo** [dana-at-cp/backdoor-apk#201]
G,day @dana-at-cp, I've noticed your work with backdoor-apk and I have to say you've done very well, I was wondering if you've ever done any work like this or similar to this, with pure JavaScript (NodeJS) by chance?

If so I'd love to have your help on upgrading an old open source RAT if you feel keen for it. 🙂

Hope to hear from you soon.

Sorry for opening this in the issues section I didn't know how else to contact you

**Comment by Morsmalleo** [comment]
Open source RAT project, you may have come across it before.

The link to my repository of it is below.
https://GitHub.com/Morsmalleo/AhMyth

I didn't create it, I'm just maintaining it, updating it, upgrading it by
adding new features and such, it's only me and one other person though so
it's slow development.

**Comment by Morsmalleo** [comment]
> 

I have a lot of plans for this project, and the more help I have from skilled developers especially in this range of things, the better.

**Comment by dana-at-cp** [comment]
@Morsmalleo Sorry but I cannot commit to anything like that but I wish you all the best.
