### ISSUE TITLE
Merging permissions of original and payload projects...

### ISSUE THREAD

**Issue by userdsp** [dana-at-cp/backdoor-apk#21]
[*] Merging permissions of original and payload projects...shuf: invalid input range: '9223372036854775807': Value too large for defined data type
shuf: invalid input range: '9223372036854775807': Value too large for defined data type
shuf: invalid input range: '9223372036854775807': Value too large for defined data type
shuf: invalid input range: '9223372036854775807': Value too large for defined data type
done.

**Comment by dana-at-cp** [comment]
Thanks for reporting this issue. I'll look into it.

**Comment by dana-at-cp** [comment]
This is now fixed on the master branch. Version: 0.1.2
