### ISSUE TITLE
 Failed to sign recompiled APK

### ISSUE THREAD

**Issue by Maxnonym** [dana-at-cp/backdoor-apk#38]
I have some issue, Failed to sign recompiled APK?
What could be the reason? Thank you

**Comment by dana-at-cp** [comment]
Have a look at issue #17 and read through the comments.

**Comment by dana-at-cp** [comment]
@Maxnonym I'm going to close this issue. If you are still having problems then please open a new issue but be sure to include some useful information. For instance, your entire run.log file would be helpful.

**Comment by Maxnonym** [comment]
Thank you!!
