### ISSUE TITLE
Failed to recompile original project.

### ISSUE THREAD

**Issue by userdsp** [dana-at-cp/backdoor-apk#39]
Is it something with apktool ver?
[run.log.zip](https://github.com/dana-at-cp/backdoor-apk/files/502175/run.log.zip)

**Comment by userdsp** [comment]
Its working at my VMware but not at my nethunter device. Can you add geolocation permission please?!

**Comment by dana-at-cp** [comment]
@userdsp That's an issue with Apktool. Are you running the latest version? Is it installed/setup properly?

https://ibotpeaches.github.io/Apktool/install/
