### ISSUE TITLE
meterpreter > wlan_geolocate [-] wlan_geolocate: Operation failed: 1

### ISSUE THREAD

**Issue by userdsp** [dana-at-cp/backdoor-apk#43]
I can see permisions at perms.tmp
  <uses-permission android:name="android.permission.ACCESS_COURSE_LOCATION"/>
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
but ...
meterpreter > wlan_geolocate
[-] wlan_geolocate: Operation failed: 1
meterpreter > geolocate
[-] geolocate: Operation failed: 1
meterpreter > 

Can you add GPS location permissions please, or if you are did, please fix them! My android phone have gps and wlan enabled, but I receive fail statement.

**Comment by dana-at-cp** [comment]
@userdsp The backdoor-apk project merges all permissions from the Metasploit meterpreter payload with the permissions of the original APK. If some of the Android meterpreter commands are not working as expected you can check the Metasploit project for known bugs. You can also create a new issue if needed.

https://github.com/rapid7/metasploit-framework
