### ISSUE TITLE
[!] Failed to align recompiled APK

### ISSUE THREAD

**Issue by maklmakl** [dana-at-cp/backdoor-apk#52]
Hi 
F.O ALL i want to thank you for your powerful project and for all you did ..

while i use your project backdoor-apk 
i got error : [!] Failed to align recompiled APK
i read the previous  solved issues 
but it still get me that message 
any help ?

& here is Run.log file : 
[run.log.tar.gz](https://github.com/dana-at-cp/backdoor-apk/files/594878/run.log.tar.gz)
thx ...

**Comment by dana-at-cp** [comment]
@maklmakl Can you do the following on your system and share the output?

```
./zipalign -h
```

```
./zipalign -c -v 4 <APK_FILE>
```
Look for zipalign in the "third-party" directory included in the backdoor-apk project.

**Comment by maklmakl** [comment]
![screenshot from 2016-11-19 20-13-08](https://cloud.githubusercontent.com/assets/23502715/20457464/aceaacea-ae94-11e6-86c1-ec0f228b784a.png)
i got this ????????????

**Comment by macbook47** [comment]
i got this error too, i think something wrong with zipalign on third party, so i manually install zipalign through apt-get install zipalign and edited backdoor-apk.sh in line 28 from
ZIPALIGN= third-party/android-sdk-linux/build-tools/23.0.3/zipalign
to
ZIPALIGN=zipalign

and voila, its worked 💃

**Comment by dana-at-cp** [comment]
@maklmakl @macbook47 This thread helps explain why you get that error on 64-bit Linux systems:

http://stackoverflow.com/questions/2716702/no-such-file-or-directory-error-when-executing-a-binary

**Comment by Mybi** [comment]
Hi when i try your program i got this error.. continuously please solve it.. i run 32 bit kali 3

[!] Failed to align recompiled APK

**Comment by FirstClickin** [comment]
**🛑🛑🛑 Here is The FIX 2019..** https://youtu.be/QfyYWioLEk4 Full Video by FirstClickin. Solved now file is Recompiling without Error
