### ISSUE TITLE
After inject and install, apllication get "force close

### ISSUE THREAD

**Issue by ichsanrendi24** [dana-at-cp/backdoor-apk#54]
hi, i tried to rebuilding infectedapk like as you. but, when i instal that, aplication get force close. i triedwith whatsapp and b612 but it's same get error force close. do you know why ? please help me. thanks

**Comment by dana-at-cp** [comment]
@ichsanrendi24 Where did you get the APK files? The source matters quite a bit.

**Comment by maklmakl** [comment]
i downloaded from Google 
any recommended sites?

**Comment by dana-at-cp** [comment]
@maklmakl I assume from the Google Play store? Also, I'm going to close the issue you created as it appears to be a duplicate of this issue.

**Comment by dana-at-cp** [comment]
@ichsanrendi24 @maklmakl I was able to recreate the issue on my updated version of Kali Linux. I can only assume that something changed in Metasploit at this time. I'll look into it ASAP.

**Comment by dana-at-cp** [comment]
@ichsanrendi24 @maklmakl Confirmed that something changed in Metasploit and the backdoor-apk code had some breakage as a result. A fix will be out later today.

**Comment by dana-at-cp** [comment]
@ichsanrendi24 @maklmakl FYI. If you know how to use 'adb' in the platform tools folder of the Android SDK then you can use 'adb logcat' to get a better idea of why the application is crashing.

**Comment by dana-at-cp** [comment]
@ichsanrendi24 @maklmakl Fixed in version 0.1.6 on master.
