### ISSUE TITLE
miss d2j-dex2jar file

### ISSUE THREAD

**Issue by islamTaha12** [dana-at-cp/backdoor-apk#56]
Please set the requirements to run the script cos I faced this issue and I got d2j-dex2jar.sh but it still occurred.
[!] Check your environment and configuration. Couldn't find: d2j-dex2jar

**Comment by dana-at-cp** [comment]
@islamTaha12 There is code that checks that all of the required programs and scripts are in the user's path. In this case, the code detected that "d2j-dex2jar" was not in your path. The code worked precisely as intended.

```
function consult_which {
  which $1 >>$LOG_FILE 2>&1
  rc=$?
  if [ $rc != 0 ]; then
    echo "[!] Check your environment and configuration. Couldn't find: $1"
    exit $rc
  fi
}
```

**Comment by traget** [comment]
Do apt-get install dex2jar :)
