### ISSUE TITLE
Processed WhatsApp APK crashes on start

### ISSUE THREAD

**Issue by meblack** [dana-at-cp/backdoor-apk#58]
the infected apk its not running on android 6

**Comment by meblack** [comment]
after install the apk , the program is not running and stopped
and no session has was created

**Comment by dana-at-cp** [comment]
@meblack Need more information.

- What is the APK?
- Where did you download the APK?
- Does the APK work before injection via backdoor-apk?
- Does the APK work on any other versions of Android?

**Comment by meblack** [comment]
i tried with whatsapp
i download it from whatsapp website
thats first try for injection test
the problem is:
its installed but not running
i test it on android 5 and 6
in both of them its not run and got the stopped error

**Comment by dana-at-cp** [comment]
@meblack I confirmed the same behavior for WhatsApp on an emulated Android 4.4 device. The problem seems to be isolated to the WhatsApp APK. This will be a low priority for me to review. How are your Android app debugging skills? Do you know the Android SDK and smali well?

**Comment by meblack** [comment]
i tried it with many apk files and none of them have not run at all.
could you please give me an apk file that work with this method properly ?

**Comment by dana-at-cp** [comment]
@meblack I use Pandora as a benchmark. It's still working as of today. Are you getting all of the APKs from the Google Play Store or from sites like apkmirror?

**Comment by meblack** [comment]
i get them from apkmirror

**Comment by dana-at-cp** [comment]
@meblack That could be part of your problem. I only use APKs from the Google Play Store.

**Comment by dana-at-cp** [comment]
@meblack Did you ever try a legit version of Pandora?

I tested it earlier today on an emulated Android 6 device and it worked fine:

```
meterpreter > sysinfo
Computer    : localhost
OS          : Android 6.0 - Linux 3.10.0+ (i686)
Meterpreter : dalvik/android

meterpreter > getuid
Server username: u0_a55

meterpreter > pwd
/data/user/0/com.pandora.android/files

meterpreter >
```

**Comment by teeknofil** [comment]
Hi, i have crash with much apk of Google Play on meterpreter_http. L'app run and this kill.
<code>
Meterpreter session 12 is not valid and will be closed
</code>

**Comment by hyzo90** [comment]
How do you get Apk file from Google Play Store ? 
the option is only to install

**Comment by dana-at-cp** [comment]
@teeknofil Make sure you are running the latest version of Metasploit and backdoor-apk.

**Comment by dana-at-cp** [comment]
@hyzo90 I use Airdroid to pull APKs off of a device.

**Comment by hyzo90** [comment]
@dana-at-cp oh . okay . will try. Tried the latest APK from Google Play but none works. App always crashes. some Apps working fine but only when the target 1st open it. but when the target closes the app, then session died. not persistent. 
maybe I have to update to the latest Jar, ApkTool and Metasploit ?

**Comment by dana-at-cp** [comment]
@hyzo90 losing the Meterpreter session when the app closes is expected behavior for the time being. The Pandora app from the Google Play Store is a good benchmark. It works nicely 100% of the time in my testing. If there are other legitimate APKs from the Google Play Store that crash on start up after processing then open a new issue so that it can be tracked.

**Comment by teeknofil** [comment]
@dana-at-cp . OS kali update. Download the Google Play app from http://apps.evozi.com/apk-downloader. All required packages are installer. It must have bug in your application. TheFatRat also has the same bug

**Comment by dana-at-cp** [comment]
@teeknofil I wouldn't consider an APK from that source legitimate. Give me a sample APK that you claim does not work.

**Comment by hyzo90** [comment]
@dana-at-cp Could you make a tutorial or anything on "how you getting the working APK for your script?"
I personally download all of APK files from APKpure.com .

**Comment by dana-at-cp** [comment]
@hyzo90 Unfortunately, you will have mixed results with APKs from sites like apkpure and apkmirror. Often times APKs from those sources have been tampered. Look into Airdroid as a way to pull legit APKs from an Android device.

**Comment by Abdulmalik5371** [comment]
@dana-at-cp for some reason the backdoor Whatsapp apk stops running after installation on victim phone...kindly help me solve the issue

**Comment by sirrsariful-web** [comment]
Mujhe WhatsApp cushr deo
