### ISSUE TITLE
Backdoored APK Location?

### ISSUE THREAD

**Issue by D347HGUN** [dana-at-cp/backdoor-apk#63]
I've successfully ran the tool and it finished with no errors but i dont know where i should find my backdoored apk
The backdoor-apk folder is placed at this directory on my pc: /root/Tools/backdoor-apk/backdoor-apk 
Any ideas where i should find the modified apk? and what should it be named after the tool finished creating it?

**Comment by dana-at-cp** [comment]
@D347HGUN It's in the last bit of the README:

```
The recompiled APK will be found in the 'original/dist' directory. Install the APK on a compatible Android device, run it, and handle the meterpreter connection via the generated resource script: msfconsole -r backdoor-apk.rc
```

Glad you figured it out. Enjoy! :)
