### ISSUE TITLE
RSA key generation fails when date detects an invalid date string in the original cert valid from line

### ISSUE THREAD

**Issue by jm537** [dana-at-cp/backdoor-apk#64]
hi   error-failed to generate RSA key???

**Comment by jm537** [comment]
![ok](https://cloud.githubusercontent.com/assets/24764776/21471770/976e9cf0-cad2-11e6-95dc-9004b4bef6d4.jpg)

**Comment by jm537** [comment]
![ok](https://cloud.githubusercontent.com/assets/24764776/21471775/d66f34dc-cad2-11e6-8aed-6166ae161488.jpg)

**Comment by dana-at-cp** [comment]
@jm537 That doesn't look good at all. Can you share the APK file and your run.log file?

**Comment by henefesto** [comment]
[run.txt](https://github.com/dana-at-cp/backdoor-apk/files/674346/run.txt)

**Comment by henefesto** [comment]
[ccleaner.zip](https://github.com/dana-at-cp/backdoor-apk/files/674348/ccleaner.zip)

**Comment by dana-at-cp** [comment]
@jm537 @henefesto I have a fix that will be on the develop branch later today.

**Comment by henefesto** [comment]
ok

**Comment by dana-at-cp** [comment]
@jm537 @henefesto The fix is no on the develop branch. Test it out and report back if you can.

**Comment by henefesto** [comment]
Okay, I'll try

**Comment by henefesto** [comment]
![captura de pantalla de 2016-12-27 15-55-15](https://cloud.githubusercontent.com/assets/24795407/21507241/05e52598-cc4d-11e6-957c-08eeff8b85dc.png)
Yeah!!

**Comment by dana-at-cp** [comment]
@henefesto Awesome! Thanks for testing the fix. It will be included in the next release.

**Comment by jm537** [comment]
[1.apk.zip](https://github.com/dana-at-cp/backdoor-apk/files/675049/1.apk.zip)
[run.txt](https://github.com/dana-at-cp/backdoor-apk/files/675051/run.txt)

**Comment by jm537** [comment]
test another system problem RSA KEY

**Comment by dana-at-cp** [comment]
@jm537 It looks like you are still running the script from the master branch. The fix for this issue is only on the develop branch at the moment.

**Comment by dana-at-cp** [comment]
@jm537 @henefesto The fix is now in v0.1.9 on the master branch. Thanks for the bug report and testing help.
