### ISSUE TITLE
Meterpreter persistence on app closure

### ISSUE THREAD

**Issue by Qurexhi** [dana-at-cp/backdoor-apk#65]
bro your tool are great but persistence hook are work only when mobile reboot. so can you add a permanent persistence hook when app close meterpreter still open..

**Comment by dana-at-cp** [comment]
@Qurexhi Thanks for the suggestion! I'll research what is possible but realize it may not be possible for various reasons.

**Comment by dana-at-cp** [comment]
@Qurexhi I found [this](http://stackoverflow.com/questions/3667022/checking-if-an-android-application-is-running-in-the-background/13809991#13809991) which may provide some promise.

**Comment by Qurexhi** [comment]
bro you try this https://github.com/n1nj4sec/pupy in this script you install app, open only one time and server connect everytime when you open but in this script function are limited. bro can you modify your script according this script??

**Comment by Qurexhi** [comment]
hope you add in your next version :+1:

**Comment by hxrofo** [comment]
@dana-at-cp : It's possible to do that, and I tried it successfully by tweaking the Manifest and MainActivity files, in addition to creating a new service, I called MyIntentService... I don't remember much, but still you can find your way by looking at this project by Giovanni Colonna
https://github.com/giovannicolonna/msfvenom-backdoor-android

**Comment by dana-at-cp** [comment]
@Qurexhi I confirmed that reboot persistence is still working.
