### ISSUE TITLE
I have some error run it..

### ISSUE THREAD

**Issue by xnianq** [dana-at-cp/backdoor-apk#66]
When I running it ,i saw..
[!] Check your environment and configuration. Couldn't find: d2j-dex2jar

**Comment by dana-at-cp** [comment]
@xnianq You don't have it installed or it's not in your user path.

**Comment by traget** [comment]
Just do apt-get install dex2jar :)

**Comment by traget** [comment]
And then if u get: Couldn't find apktool, do apt-get install apktool
