### ISSUE TITLE
Use backdoor outside lan

### ISSUE THREAD

**Issue by Abdulmalik5371** [dana-at-cp/backdoor-apk#67]
Dana-at-cp, i was wondering if the backdoor-apk can be used outside the LAN...and if its possible kindly guide as to how i can accomplish this. Thanks alot, and congrats on the backdoor it really works wonders for me.

**Comment by dana-at-cp** [comment]
@Abdulmalik5371 Yes, of course. Simply enter the IP or FQDN of a host on the Internet that is prepared to receive the Meterpreter session.

**Comment by Abdulmalik5371** [comment]
Thanks
