### ISSUE TITLE
d2j-dex2jar

### ISSUE THREAD

**Issue by traget** [dana-at-cp/backdoor-apk#68]
Hi!
Sorry to bother.. 
I'm trying to execute apk-backdoor.sh, but I get this error:
[!] Check your environment and configuration. Couldn't find: d2j-dex2jar

I know your script works fine cuz I guess it's supposed to check some requirements that I do not met.. 

My question is what do I need to do to get rid of this warning. :P

**Comment by traget** [comment]
I feel a little bit dumb right now cuz I was trying to do: apt-get install d2j-dex2jar :(
For any other person who gets stumbled upon this, you need to do apt-get install dex2jar.. 
I really feel dumb. :\

**Comment by dana-at-cp** [comment]
@traget Haha! No problem. Glad you got it sorted.

**Comment by pacman-vzla** [comment]
I did apt-get install dex2jar and I get the error "Could not locate the dex2jar package"

**Comment by jorgeclenio** [comment]
I tried installing the apt-get install dex2jar package but I could not (it could not find the package), what can I do about it?

**Comment by sh1nta** [comment]
i have this issue Failed to run dex2jar on RAT APK file

**Comment by KunalShelarKS** [comment]
same isse
