### ISSUE TITLE
 application always get ' unfortunately app has stopped ' 

### ISSUE THREAD

**Issue by e403** [dana-at-cp/backdoor-apk#74]
after android app injection and install the final app i always get ' unfortunately app has stopped '
i use parrot sec os linux 3.4
i download apk from googleplay , apkpure .... any site
and it still the problem !!

**Comment by dana-at-cp** [comment]
@e403 Can you try Pandora from the Google Play Store? That app is a good baseline and has proven to be very stable after injection.

**Comment by e403** [comment]
i get this bro 

[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
[*] Generating RSA key for signing...done.
[*] Signing recompiled APK...done.
[*] Verifying signed artifacts...done.
[*] Aligning recompiled APK...done.
[!] Failed to align recompiled APK

**Comment by dana-at-cp** [comment]
@e403 Can you do the following for me on your system?

```
root@kali:~/Code/github/backdoor-apk/backdoor-apk/third-party/android-sdk-linux/build-tools/23.0.3# pwd
/root/Code/github/backdoor-apk/backdoor-apk/third-party/android-sdk-linux/build-tools/23.0.3
root@kali:~/Code/github/backdoor-apk/backdoor-apk/third-party/android-sdk-linux/build-tools/23.0.3# ./zipalign 
Zip alignment utility
Copyright (C) 2009 The Android Open Source Project

Usage: zipalign [-f] [-p] [-v] [-z] <align> infile.zip outfile.zip
       zipalign -c [-v] <align> infile.zip

  <align>: alignment in bytes, e.g. '4' provides 32-bit alignment
  -c: check alignment only (does not modify file)
  -f: overwrite existing outfile.zip
  -p: page align stored shared object files
  -v: verbose output
  -z: recompress using Zopfli
root@kali:~/Code/github/backdoor-apk/backdoor-apk/third-party/android-sdk-linux/build-tools/23.0.3#
```

**Comment by e403** [comment]
please wait ..

**Comment by e403** [comment]
I can't understand the following ?
i go to the path 
"backdoor-apk-master/backdoor-apk/third-party/android-sdk-linux/build-tools/23.0.3"
and these files only exist :
dx  lib  NOTICE.txt  zipalign

**Comment by dana-at-cp** [comment]
@e403 Once in that directory try to execute the zipalign binary. For example:

```
# ./zipalign
```

**Comment by dana-at-cp** [comment]
@e403 Can you share the output of running zipalign via the CLI?

**Comment by dana-at-cp** [comment]
Closing this issue for now. Create a new issue if needed.
