### ISSUE TITLE
[Feature Request] Persistent Backdoor

### ISSUE THREAD

**Issue by its-arun** [dana-at-cp/backdoor-apk#76]
Would it be possible for you to add persistent backdoor to apk into this script? Currently the process is manual and has to be done using Android Studio or Maven.

https://github.com/kaeljurk/metasploit-android

Also please avoid scanning with Virus Total. You may use NoDistribute.com.

**Comment by dana-at-cp** [comment]
@its-arun There is reboot persistence via a the service mechanism. Am I missing something?

**Comment by its-arun** [comment]
@dana-at-cp yes it seems like reboot persistence

**Comment by dana-at-cp** [comment]
@its-arun That capability already exists in the embedded RAT payload. Is it not working?

**Comment by dana-at-cp** [comment]
@its-arun Closing this issue as the feature already exists in the latest version.
