### ISSUE TITLE
Help how to set up proguard5.2.1 environment and configuration 

### ISSUE THREAD

**Issue by rielinux** [dana-at-cp/backdoor-apk#79]
Hi there... need help to set up proguard5.2.1 environment and configuration ( i allready have all depedencies and proguard 5.2.1)  but i still have this notification on my Kali rolling 

[*] Running backdoor-apk.sh v0.1.9 on Thu Feb  9 20:30:55 2017
[!] Check your environment and configuration. Couldn't find: third-party/proguard5.2.1/lib/proguard

Thanks...

**Comment by dana-at-cp** [comment]
@rielinux Hello. Did you remove the proguard directory that ships with backdoor-apk?

**Comment by rielinux** [comment]
Nope, i didn't remove any proguard file and folder, it still there...

any suggestion ?

**Comment by dana-at-cp** [comment]
@rielinux Did you move any files or directories around? Since proguard is bundled with the project, the error you are getting doesn't really make sense. If things were moved around then it does make sense.

Have you tried to do a git clone to get a clean working directory for the project?

**Comment by rielinux** [comment]
Thank man @dana-at-cp , now that solve my problem, i tried do a new git clone again and my problem solved. Thank you thank you.... #case-closed

**Comment by dana-at-cp** [comment]
@rielinux No problem. Glad it's sorted.

**Comment by nada94** [comment]
i have the same problem and i don't understand your solution , please can you write the code to fix it for me , thank you
