### ISSUE TITLE
Persistence 

### ISSUE THREAD

**Issue by harshil2105** [dana-at-cp/backdoor-apk#80]
According to me a person has to be constantly using the compromised  as soon  as a person exits the apk or stop using the Apk I loose the shell..You can make a persistance.sh which we could upload in there system and then drop into shell then execute this persistence.sh file to get a shell even if he/she removes the app from there activity manager

**Comment by harshil2105** [comment]
I could easily add persistance on a straight payload APk which is not embedded with any other apk but my .sh script fails in your case

**Comment by dana-at-cp** [comment]
@harshil2105 Can you share the shell script that works with the plain Metasploit payload APK? You should be able to attach it in a comment.
