### ISSUE TITLE
[!]Failed to recompile original project with backdoor

### ISSUE THREAD

**Issue by DanielJangua** [dana-at-cp/backdoor-apk#84]
Hello, I'm not able to recompile the apk, I already tried with different apks and I had the same problem. I am using Kali Linux 64bit, backdoor-apk v0.2.0, apktool v2.2.1.
Do you have any idea what might be causing the error? Thanks in advance!

Run.log file:

I: Using Apktool 2.2.1-dirty
I: Checking whether sources has changed ...
I: Smaling smali folder into classes.dex ...
I: Checking whether sources has changed ...
I: Smaling smali_classes4 folder into classes4.dex ...
I: Checking whether sources has changed ...
I: Smaling smali_classes3 folder into classes3.dex ...
I: Checking whether sources has changed ...
I: Smaling smali_classes2 folder into classes2.dex ...
Original / smali_classes2 / com / snapchat / android / LandingPageActivity.smali [9405,4] Invalid register: v18. Must be between v0 and v15, inclusive.
Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: com / snapchat / android / LandingPageActivity.smali
At brut.androlib.src.SmaliBuilder.buildFile (SmaliBuilder.java:77)
At brut.androlib.src.SmaliBuilder.build (SmaliBuilder.java:61)
At brut.androlib.src.SmaliBuilder.build (SmaliBuilder.java:38)
At brut.androlib.Androlib.buildSourcesSmali (Androlib.java:405)
At brut.androlib.Androlib.buildNonDefaultSources (Androlib.java:351)
At brut.androlib.Androlib.build (Androlib.java:293)
At brut.androlib.Androlib.build (Androlib.java:264)
At brut.apktool.Main.cmdBuild (Main.java:227)
At brut.apktool.main.main (Main.java:84)
Forcing cleanup due to failure or error state!

**Comment by dana-at-cp** [comment]
@DanielJangua Apktool has limitations and known issues. It looks like you've encountered one of those issues.
