### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by peterpt** [dana-at-cp/backdoor-apk#85]
Thanks for your project .
I will implement your code with some changes adapted to one of the projects i am working at : 
https://github.com/Screetsec/TheFatRat

after i adjust your script to work in sync with TheFatRat and push my changes to the git , feel free to join us and make improvements in case you want to contribute .

In changes that i am doing , i will leave your credits there .

**Comment by dana-at-cp** [comment]
@peterpt Cool. Thanks for the heads up.
