### ISSUE TITLE
Update packages

### ISSUE THREAD

**Issue by peterpt** [dana-at-cp/backdoor-apk#86]
You should update packages of tool to 
android sdk 25.2.3 : https://developer.android.com/studio/index.html#download
proguard 5.3.2 :  https://sourceforge.net/projects/proguard/files/proguard/

**Comment by motasimali** [comment]
@peterpt I have updated proguard successfully in thirdparty folder but i am unable to update sdk folder. Have you done this on your side ? if so then guide me

**Comment by peterpt** [comment]
I did not updated here the packages manually , i did not tested here  none of them because i am occupied with other things .
However , backdoor-apk have the external tools needed in its folder , but i think you can install those tools updated outside from its directory and point the backdoor-apk script variables to system updated tools .

to install proguard,zipalign,dx on your system , all you have to do is : 
apt-get install aapt lib32stdc++6 lib32z1 lib32z1-dev zipalign proguard dx android-sdk

depending on your main linux OS repository , these tools may exist or not , i know that debian repository have at least these tools to be installed in their repo : aapt lib32stdc++6 lib32z1 lib32z1-dev zipalign proguard dx

and kali repository have the : android-sdk .

after that all needed is change the variables paths in backdoor-apk.sh to : 

PROGUARD=proguard
DX=dx
ZIPALIGN=zipalign

but some other stuff inside the script will need changes .
ex:
proguard config file must be pointed to a variable program path , so proguard can read it : 
$PROGUARD @android.pro >>$LOG_FILE 2>&1     <- must be changed

and other variables .

sometimes if an error appears is not because the backdoor-apk have some bug , it is because the apk file you are using the programmers used different configurations on the apk file , and backdoor-apk is unable to detect it .

One of the main errors of this app  is that is pre configured to look for the main file inside original apk that starts up the apk in android to inject the payload there , this way everytime the victim starts the apk , the attacker can get access to that victim device . But inside the original apk file exists hundreds of configurations , and each one is for a command used in apk or a window that pops up in original apk when you are running it .
If the original programmer changes the startup config filename inside the apkfile , the this and other tools like this one will give an error on injecting the payload into apk because it can not finnd that specific file inside the apk where was suppose to inject the code .

backdoor-apk is pre-configure to look for a specific original file inside the original apk file to merge the payload  , and if not find that file gives an error .

Other tools when do not find that specific generic file (because original apk programmer change it name) , pops up a message for user to choose where wants to merge the payload .

here it is an example with latest firefox apk : 
https://s16.postimg.org/7mkmpytr9/hook.png

Sometimes is more complicated to rebuild the apk file than everyone thinks .

**Comment by dana-at-cp** [comment]
@peterpt I'll look into getting these bits updated in the next release.
