### ISSUE TITLE
Locating smali file to hook in original project...grep: android.intent.category.LAUNCHER: File o directory non esistente

### ISSUE THREAD

**Issue by BArdokk** [dana-at-cp/backdoor-apk#87]
Locating smali file to hook in original project...grep: android.intent.category.LAUNCHER: File o directory non esistente
grep: android.intent.category.LAUNCHERgrep: android.intent.action.MAIN: File o directory non esistente
: File o directory non esistente
grep: android.intent.category.LAUNCHER: File o directory non esistente
grep: android.intent.action.MAIN: File o directory non esistente
done.
[!] Failed to locate smali file to hook

hello, you can help me with this problem? Thanks in advance

**Comment by peterpt** [comment]
try with other apk to test .
read here why that happens : 
https://github.com/dana-at-cp/backdoor-apk/issues/86

**Comment by dana-at-cp** [comment]
@BArdokk Please share the APK file. You can attach it to this issue on GitHub.

**Comment by BArdokk** [comment]
TNX for all

**Comment by dana-at-cp** [comment]
@BArdokk TNX is the APK used? Can you attach it?

**Comment by thestropker** [comment]
i have same problem.

**Comment by thestropker** [comment]
Use another apk and work
