### ISSUE TITLE
error generating date

### ISSUE THREAD

**Issue by aleemladha** [dana-at-cp/backdoor-apk#92]
Invalid date.
![screenshot from 2017-03-09 13-58-35](https://cloud.githubusercontent.com/assets/26311391/23769304/ed273712-04dc-11e7-97aa-0cc47423dba3.png)

**Comment by aleemladha** [comment]
Error signing the backdoor
![image](https://cloud.githubusercontent.com/assets/26311391/23785120/11d2df36-0577-11e7-99d1-aa1f856dcd53.png)

**Comment by dana-at-cp** [comment]
@aleemladha Please share the APK file or files you are working with that are producing these errors.

**Comment by aleemladha** [comment]
https://dl.dropboxusercontent.com/u/103296725/cp-apk.zip

**Comment by dana-at-cp** [comment]
@aleemladha I did not get the "invalid date" error with any of the APK files you shared. 3 out of 4 of the APK files were processed properly with v0.2.1 of backdoor-apk. The one APK file that was not processed correctly appears to be a non-standard APK that didn't fully decompile or is missing framework files required to decompile properly.
