### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by peterpt** [dana-at-cp/backdoor-apk#93]
Hi , i have been testing your new master repo and i found a few bugs .
here are some steps i did so far to bypass some bugs :  
for some reason , your detection on "if exists files in original decompiled apk folder" had some issue , i had to by pass that check by ignoring the "if" code at lines : 271 to 274

then everything went well until i get this error :  
- Failed to run dx on proguard processed jar file
(the good thing is the log on the tool , that i checked this error : 
dx unsupported major.minor version 52.0)

i had to ignore your last upgrade on dx file in your third party folder and use my OS dx tool .
for that i went to startup variables at line 29 and changed it to "dx" only , so it can use my system installed DX tool .

the i got another bug when the tool tries to detected the default smali file to hook and get an error : 
https://s12.postimg.org/s9vztm0h9/backdoor_apk_001.png

at this part i got stuck because log did not output the cause of the error , only in the image before i knew the cause .
here it is the log :  
http://pastebin.com/dgLpnx0F

(Note : i did not had much time yet to concentrate on your new changes and discover the reason , but as soon as i get some time i will check it out .)
for what i could see until now , your android third party upgrade must be back to 23.0 version , because of the dx call , or instead using your folder tools , you can make a simple install.sh file that installs from repository those tools , so you do not have to worry about them .
on debian , to install proguard you just have to write "apt-get install proguard" , every debian repo have this file , and in proguard config you can create a variable based on your tool "path" config , pointing to proguard configuration .
ex : 
instead : $PROGUARD @android.pro >>$LOG_FILE 2>&1

you can set a variable like : 
proconfig=$MY_PATH/android.pro

and use it as : 
$PROGUARD @$proconfig >>$LOG_FILE 2>&1

The dx tool , according to debain repo , they have those tools you need under this package name : 
google-android-build-tools-installer
so , "apt-get install google-android-build-tools-installer"
will fix this dependency .
https://s8.postimg.org/sweq1pnvp/repo_002.png

my repository is not the Kali repository , it is the devuan repo witch is a debian jessie fork .
in kali people just have to install it by : "apt-get install aapt dx apktool" etc ...

See if you can figure out (when you get time) , why does tool did not found an hook and why did not popup options for user to choose , like you told you were implementing .

During this weekend i will check the all other stuff , and make some tests .
I have your current repo cloned in my git , i will probably make a setup script to fix all those dependencies depending on user OS detected , and i will test them here .
If everything went good then i will upload the file to my git for you to check it out , and in mean time i will see if we can get rid of those third party folder tools you use .

**Comment by peterpt** [comment]
Well , it looks that the output of backdoor apk depends on tools versions used .
I also noted that facebook.apk is the only one giving me issues after changing somethings here .
I am uploading a video to youtube showing all my changes in realtime and then testing new apks for you to see .
I also show in video how to bypass some errors that i encounter on some apps that backdoor-apk uses .

Finally , i will define a temp directory for backdoor-apk to work with payload and original file inside it .
On this video i show the changes using system instalation of dx app , but backdoor-apk still uses your proguard version .
I will change that .
Note: i will edit this post with youtube link for you to see as soon as i upload it .

**Comment by dana-at-cp** [comment]
@peterpt Hello. I'm sorry but it's not clear what is being reported. If you have a bug to report then please do the following:

* Be as concise and accurate as possible
* Describe the environment (version of backdoor-apk, has it been modified, etc.)
* Attach the APK file used so that I (and others) can attempt to reproduce

**Comment by peterpt** [comment]
Hi , well , it was a bug that i corrected in real time .
- backdoor-apk does not work if the original apk is outside backdoor-apk main folder

Some apks give issues , but in generally the tool is wornking fine , the video have 50 minutes because i was not expecting so many susprises when i was testing the apks .
The man objective on video was to show you that if you try to compile a rat apk file on an app outside backdoor-apk folder then it gave issues , and at same time to show you that your tool was unable to work with the facebook apk .

But i got in the way of that process other unexpected issues that i was able to fix , this is why the video took so long time .

Anyway , you should create a few lines of code to copy the original apk file inside backdoor-apk and then work with that file inside your tool folder .

If you test there this command : 
./backdoor-apk.sh   /someapp.apk 

it will give you an error along the way .

backdoor-apk only works fine if the apk file is on main tool folder :  
./backdoor-apk.sh someapp.apk
