### ISSUE TITLE
too many arguments - failed to add hook .

### ISSUE THREAD

**Issue by peterpt** [dana-at-cp/backdoor-apk#95]
i was trying to compile youtube.apk when i got this message :  
[*] Adding hook in original smali file..../backdoor-apk.sh: line 96: [: too many arguments
done.

the log says :  
http://pastebin.com/8Hqw3rzw

I have created a folder with some random apks i downloaded that backdoor-apk is unable to find hook points to inject the smali file .
if you check this page you will see 2 folders : 
https://www.mediafire.com/folder/d64gcc0hqa5l7/notworking

(Issues related to hook points) folder = backdoor-apk was unable to find a hook

(issues related to aapt version) folder = on this folder are the apks where backdoor-apk found a hook point but in the end was unable to compile the apk file .
My guess is that this issue is related to aapt version witch may be to recent or too old to compile the apk . However my version is 23 (i think) , and i will test with other versions of aapt to see if it fixes .

My friend , if you get sometime then look only to those 3 apks where no hook was found , maybe adding some more search strings options to backdoor-apk when it tries to get a point may fix the issue . In mean while i will write here soon with my conclusions on the aapt issues .

Other apks that i tested and were compiled successfully with my aapt version were : 
facebooklite
skype
whatsapp

**Comment by peterpt** [comment]
some news : 
1st - unsupported minor version error on your proguard is related to user openjdk version .

This means that user must install openjdk 8 and change java alternatives to openjdk8 .
"apt-get install openjdk-8-jre openjdk-8-jdk"
and
update-alternatives --config java    
and selecting openjdk 8 will solve proguard issue .

aapt in user system will probably not compatible with the aapt android sdk 25 you have in your third-party package .
Solution i made was removing aapt from system and creating a symlink in /usr/bin directly to your aapt version in third party directory .

Testing twitter.apk witch was giving me compiling issues , it still continues to give issues :  

on this next log you can see that the hook point is made , but somehow apktool is unable to compile the package :  
http://pastebin.com/7uKJuN8i

but i get an error ahead related to android framework package according to apktool website : 
https://ibotpeaches.github.io/Apktool/documentation/

tomorrow i will investigate this issue more further , in mean while it would be interesting if you could test too the twitter.apk to see if you get the same issue , you can find it on the mediafire link i posted previously on my 1st post .

**Comment by peterpt** [comment]
with apktool 2.2.2 in third party tools solve all compilation issues with aapt .
However , those files where the tool can not find an hook point will stay in the same situation .

**Comment by dana-at-cp** [comment]
@peterpt Thanks. I will look into the the specific APK issues. I saw your pull request for Apktool 2.2.2 ... I'll investigate this further to see if it resolves some of the current Apktool issues.

**Comment by GameonRoki** [comment]
Sir am struck in Unable to find a hook point /tmp/d20180630-2334-ak3cth/original/smali*/ClientApplicationSplittedShell.smali 


someone please resolve this

**Comment by kamru** [comment]
i was trying to compile cclean.apk when i got this message :
[!] Failed to add hook

**Comment by NaheelSalman** [comment]
./backdoor_apk: line 107: [: too many arguments
done.
 [!] Failed to add hook
![screenshot from 2018-07-30 16-46-29](https://user-images.githubusercontent.com/39267623/43422610-3e062eba-9418-11e8-80df-714319b5c936.png)
