### ISSUE TITLE
Backdoor-apk implemented in fatrat 1.9

### ISSUE THREAD

**Issue by peterpt** [dana-at-cp/backdoor-apk#97]
hi , i am just posting to say that backdoor-apk was implemented in TheFatRat Tool at : 
here : 
https://github.com/peterpt/TheFatRat/

and here : 
https://github.com/Screetsec/TheFatRat

we made some changes to your code to be able to work with fatrat .

**Comment by dana-at-cp** [comment]
@peterpt Ok. Thanks for the heads up.
