### ISSUE TITLE
Cannot find resource script: backdoor-apk.rc

### ISSUE THREAD

**Issue by kn0wledge** [dana-at-cp/backdoor-apk#98]
Hi @dana-at-cp ,

im sorry for the  very noob question, but i compiled the apk and ran: 
`msfconsole -r backdoor-apk.rc`
for the handler but i got the below error : 

> Cannot find resource script: backdoor-apk.rc

any ideas? ?

**Comment by dana-at-cp** [comment]
@kn0wledge Can you share your command-line output and the run.log file?
